

######################################################################
#
# Makefile.unix.  Generated automatically from Makefile.in by m4.
#


#### Variables specific to this directory ####

# Current directory relative to the top-level build directory
curdir = lib/clu2c

# Top-level build directory
topdir = ../..

# Default flags to plink
DEFAULT_PLINKFLAGS = -x

# All the flags to plink
ALL_PLINKFLAGS = $(DEFAULT_PLINKFLAGS) $(PLINKFLAGS)

# Command line to fake clu2c execution
FAKE_CLU2C = sh $(top_srcdir)/fakeclu.sh

# Command line to execute plink
REAL_PLINK = $(PLINK) $(ALL_PLINKFLAGS) -o $(POUT).c $(CLU_INT)

# Command line to fake plink execution
FAKE_PLINK = $(LN_S) $(srcdir)/pretrans/$(POUT).c $(POUT).c

# Default flags to the C compiler
DEFAULT_CFLAGS = -I$(top_srcdir)/include -w -I$(topdir)

# All the flags to the C compiler
ALL_CFLAGS = $(DEFAULT_CFLAGS) $(CFLAGS)

# Archive file
ARCHIVE = ../libclu2c.a


#### Source files ####

# C source files
C_SRC = $(C_SRC_1) $(C_SRC_2)
C_SRC_1 = acos.c asin.c atan.c atan2.c clurt.c cos.c cosh.c dfltroot.c
C_SRC_2 = exp.c log.c log10.c sin.c sinh.c sqrt.c tan.c tanh.c

# Interface specification files
SPC_SRC = $(SPC_SRC_1)
SPC_SRC_1 = dfltroot.spc math.spc pstream.spc

# CLU source files
CLU_SRC = $(CLU_SRC_1) $(CLU_SRC_2) $(CLU_SRC_3) $(CLU_SRC_4) $(CLU_SRC_5) $(CLU_SRC_6) $(CLU_SRC_7) $(CLU_SRC_8) _fs_dos.clu _fs_unix.clu
CLU_SRC_1 = cur_dir.clu de_names.clu dir_fn.clu f_date.clu f_exists.clu
CLU_SRC_2 = filetype.clu fn_abs.clu fn_apply.clu fn_asdir.clu
CLU_SRC_3 = fn_drive.clu fn_f_dir.clu fn_f_suf.clu fn_isabs.clu
CLU_SRC_4 = fn_nodir.clu fn_pdir.clu fn_simpl.clu fn_tostr.clu
CLU_SRC_5 = fn_xhome.clu getenv.clu getopt.clu home_dir.clu input_st.clu
CLU_SRC_6 = intopars.clu intounpa.clu intxpars.clu intxunpa.clu
CLU_SRC_7 = progargs.clu progname.clu pstream.clu rtenv.clu split_de.clu
CLU_SRC_8 = terminat.clu system.clu

# Equate files
EQU_SRC = getopt.equ

# Miscellaneous source files
MISC_SRC = ChangeLog Makefile.in README LIB.xld mkdfltrt.c

# All the source files
ALL_SRC = $(C_SRC) $(SPC_SRC) $(CLU_SRC) $(EQU_SRC) $(MISC_SRC)


#### Created files ####

# Object files compiled from C source files
C_OBJ = $(C_OBJ_1) $(C_OBJ_2)
C_OBJ_1 = acos.o asin.o atan.o atan2.o clurt.o cos.o cosh.o dfltroot.o
C_OBJ_2 = exp.o log.o log10.o sin.o sinh.o sqrt.o tan.o tanh.o

# Intermediate C files translated from CLU files
CLU_INT = $(CLU_INT_1) $(CLU_INT_2) $(CLU_INT_3) $(CLU_INT_4) $(CLU_INT_5) $(CLU_INT_6) $(CLU_INT_7) $(CLU_INT_8) _fs_dos.c _fs_unix.c
CLU_INT_1 = cur_dir.c de_names.c dir_fn.c f_date.c f_exists.c
CLU_INT_2 = filetype.c fn_abs.c fn_apply.c fn_asdir.c
CLU_INT_3 = fn_drive.c fn_f_dir.c fn_f_suf.c fn_isabs.c
CLU_INT_4 = fn_nodir.c fn_pdir.c fn_simpl.c fn_tostr.c
CLU_INT_5 = fn_xhome.c getenv.c getopt.c home_dir.c input_st.c
CLU_INT_6 = intopars.c intounpa.c intxpars.c intxunpa.c
CLU_INT_7 = progargs.c progname.c pstream.c rtenv.c split_de.c
CLU_INT_8 = terminat.c system.c

# Object files compiled from intermediate C files
CLU_OBJ = $(CLU_OBJ_1) $(CLU_OBJ_2) $(CLU_OBJ_3) $(CLU_OBJ_4) $(CLU_OBJ_5) $(CLU_OBJ_6) $(CLU_OBJ_7) $(CLU_OBJ_8)
CLU_OBJ_1 = cur_dir.o de_names.o dir_fn.o f_date.o f_exists.o
CLU_OBJ_2 = filetype.o fn_abs.o fn_apply.o fn_asdir.o
CLU_OBJ_3 = fn_drive.o fn_f_dir.o fn_f_suf.o fn_isabs.o
CLU_OBJ_4 = fn_nodir.o fn_pdir.o fn_simpl.o fn_tostr.o
CLU_OBJ_5 = fn_xhome.o getenv.o getopt.o home_dir.o input_st.o
CLU_OBJ_6 = intopars.o intounpa.o intxpars.o intxunpa.o
CLU_OBJ_7 = progargs.o progname.o pstream.o rtenv.o split_de.o
CLU_OBJ_8 = terminat.o system.o

# Base name of output file of plink
POUT = op-table

# Pre-translated C files
PRE = $(CLU_INT) $(POUT).c

# All the object files
ALL_OBJ = $(CLU_OBJ) $(C_OBJ) _fs.o


#### Variables for source code maintenance ####

# Non-source files included in the distribution
NON_SRC = Makefile.dos Makefile.unix version.equ fakeclu.bat

# All the files included in the distribution
DIST = $(ALL_SRC) $(NON_SRC)

# Default flags to m4
DEFAULT_M4FLAGS = -I$(top_srcdir)/mk

# All the flags to m4
ALL_M4FLAGS = $(DEFAULT_M4FLAGS) $(M4FLAGS)


#### Rules for standard targets ####

# Compiles the entire program
all: archive $(POUT).c

# Copies all the products
install: installdirs all
	@for i in $(SPC_SRC); do \
		echo $(INSTALL_DATA) $(INSTALLFLAGS) $(srcdir)/$$i $(clu2c_libdir)/$$i; \
		$(INSTALL_DATA) $(INSTALLFLAGS) $(srcdir)/$$i $(clu2c_libdir)/$$i; \
	done
	$(INSTALL_DATA) $(INSTALLFLAGS) $(srcdir)/getopt.equ $(clu2c_libdir)/getopt.equ

# Removes installed files
uninstall:

# Makes mostly clean
mostlyclean:
	rm -f archive
	rm -f _fs.o dfltroot.h
	rm -f $(C_OBJ)
	rm -f $(CLU_OBJ)

# Makes clean
clean:
	rm -f archive
	rm -f SPC.lib clu2c.time $(POUT).c
	rm -f _fs.o dfltroot.h
	rm -f $(C_OBJ)
	rm -f $(CLU_INT)
	rm -f $(CLU_OBJ)

# Makes clean as disributed
distclean:
	rm -f Makefile Makefile.top
	rm -f archive
	rm -f SPC.lib clu2c.time $(POUT).c
	rm -f _fs.o dfltroot.h
	rm -f $(C_OBJ)
	rm -f $(CLU_INT)
	rm -f $(CLU_OBJ)

# Makes really clean
realclean:
	rm -f Makefile Makefile.top
	rm -f archive
	rm -f SPC.lib clu2c.time $(POUT).c
	rm -f _fs.o dfltroot.h
	rm -f $(C_OBJ)
	rm -f $(CLU_INT)
	rm -f $(CLU_OBJ)

# Creates tag file
TAGS:

# Creates info file
info:

# Creates distribution
dist: $(DIST) $(PRE)
	@$(top_srcdir)/config/makedist $(distname) $(curdir) $(DIST)
	@$(top_srcdir)/config/makedist -p $(distname) $(curdir) $(PRE)

# Does some check
check:


#### Rules specific to this directory ####

# Creates _fs.o from _fs_*.c
_fs.o: $(srcdir)/_fs_$(FS_TYPE).c
	$(CC) $(ALL_CFLAGS) -c $(srcdir)/_fs_$(FS_TYPE).c -o _fs.o

# Creates dfltroot.o
dfltroot.o: $(srcdir)/dfltroot.c dfltroot.h
	$(CC) $(ALL_CFLAGS) -I. -c $(srcdir)/dfltroot.c

# Creates dfltroot.h
dfltroot.h: Makefile
	echo \#define CLU2C_ROOTDIR \"$(clu2c_rootdir)\" >dfltroot.h

# Prepares installation directory
installdirs:
	test -d $(clu2c_rootdir) || mkdir $(clu2c_rootdir)
	test -d $(clu2c_libdir) || mkdir $(clu2c_libdir)
	test -d $(clu2c_libdir) || mkdir $(clu2c_libdir)

# Creates all the C files
cfiles: clu2c.time $(POUT).c

# Translates all the CLU source files to C files
clu2c.time: $(CLU_SRC) $(srcdir)/version.equ
	$(CLU2C) $(CLU2CFLAGS) --make
	echo clu2c.time > clu2c.time

# Pre-link
$(POUT).c: $(CLU_INT)
	$(PLINK_METHOD)

# Archives object files in this directory
archive: $(ALL_OBJ)
	$(AR) $(ARFLAGS) $(ARCHIVE) _fs.o
	$(AR) $(ARFLAGS) $(ARCHIVE) $(CLU_OBJ)
	$(AR) $(ARFLAGS) $(ARCHIVE) $(C_OBJ)
	$(RANLIB) $(ARCHIVE)
	echo archive > archive

# Creates makefiles for this directory and all the subdirectories
mkfiles:
	cat Makefile.top $(topdir)/config.mk $(srcdir)/Makefile.unix > Makefile

# Forces a particular target to be made
always:


#### Suffix rules ####

.SUFFIXES:
.SUFFIXES: .o .c .clu

# Compiles CLU files
.clu.c:
	rm -f clu2c.time
	$(MAKE) clu2c.time

# Compiles C file to get object file
.c.o:
	$(CC) $(ALL_CFLAGS) -c $<


#### Rules for source code maintenance ####

# Creates version.equ
version.equ: $(top_srcdir)/config/configmk.in
	rm -f version.equ
	echo "% version.equ.  Generated automatically by make." >version.equ
	echo "version = \"$(VERSION)\"" >>version.equ
	chmod 444 version.equ

# Creates fakeclu.bat
fakeclu.bat: Makefile
	@echo creating fakeclu.bat
	@echo echo off > fakeclu.bat
	@echo rem fakeclu.bat.\  Generated automatically by make. >> fakeclu.bat
	@for i in $(CLU_INT); do \
		echo echo preparing $$i >>fakeclu.bat; \
		echo "if not exist $$i copy pretrans\\$$i $$i >nul" >> fakeclu.bat; \
	done

# Deletes all files created by making cfiles
cfiles-clean:
	rm -f $(CLU_INT) $(POUT).c SPC.lib clu2c.time

# Processes m4 files
m4:
	@for os in unix dos; do					\
	    mk=Makefile.$$os;						\
	    echo creating $$mk;						\
	    $(M4) $(ALL_M4FLAGS) -DOSTYPE=$$os Makefile.in >$$mk.new;	\
	    if test ! $$?; then						\
		echo $$mk is unchanged;					\
		rm -f $$mk.new;						\
		exit 1;							\
	    elif cmp -s $$mk $$mk.new 2>/dev/null; then			\
		echo $$mk is unchanged;					\
		rm -f $$mk.new;						\
	    else							\
		rm -f $$mk;						\
		mv $$mk.new $$mk;					\
	    fi;								\
	done

# Creates dos distribution
dosdist: $(DIST) $(PRE)
	@$(top_srcdir)/config/makedist -d $(dos_distname) $(curdir) $(DIST)
	@$(top_srcdir)/config/makedist -d -p $(dos_distname) $(curdir) $(PRE)

# Creates the list of source files
source-list:
	@if [ $(curdir) = . ]; then\
	    cp /dev/null source-list;\
	    for i in $(ALL_SRC); do\
		echo $$i >>source-list;\
	    done;\
	else\
	    for i in $(ALL_SRC); do\
		echo $(curdir)/$$i >>$(topdir)/source-list;\
	    done;\
	fi
