/* Generated by clu2c (version 1.99.3) */
/* option, optimize time */
/* depend,_check_directory_entry*/
/* depend,_current_directory,_external_getcwd*/
/* depend,_directory_with_drive*/
/* depend,_is_atomic_directory*/
/* depend,_is_path_delimiter*/
/* depend,_null_device_name,file_name*/
/* depend,_path_delimiter*/

#include <clu2c.h>

static STRING_REP(1) str1 = {1, {'/'}};
static STRING_REP(4) str2 = {4, {'/', 'd', 'e', 'v'}};
static STRING_REP(4) str3 = {4, {'n', 'u', 'l', 'l'}};

/* begin module */
/* c_function_name, AF__check__directory__entry */
/* clu_operation_name, _check_directory_entry */
int AF__check__directory__entry(LVname, LVsuffix)
     object LVname;
     object LVsuffix;
{
  object LVnsize= 0;
  object LVssize= 0;
  int t1, t2;
  /* begin body */
  LVnsize = OMstring_Dsize(LVname);
  LVssize = OMstring_Dsize(LVsuffix);
  if (OMint_Dgt(LVnsize, 255))
    {
      if (OFstring_Dsubstr(LVname, 1, 255) == SIG)
        {
	  goto except0;
        }
      LVname = retval_area[0];
      LVsuffix = SLNULL;
    }
  else
    {
      t1 = FALSE;
      if (OMint_Dequal(LVnsize, 254))
        {
	  if (OMint_Dgt(LVssize, 0))
	    {
	      t1 = TRUE;
	    }
        }
      if (t1)
        {
	  OFstring_Dappend(LVname, '.');
	  LVname = retval_area[0];
	  LVsuffix = SLNULL;
        }
      else
        {
	  if (OMint_Dgt(OMint_Dadd(OMint_Dadd(LVnsize, LVssize), 1), 255))
	    {
	      if (OFstring_Dsubstr(LVsuffix, 1, OMint_Dsub(OMint_Dsub(255, LVnsize), 1)) == SIG)
	        {
		  goto except0;
	        }
	      LVsuffix = retval_area[0];
	    }
        }
    }
  t1 = LVname;
  t2 = LVsuffix;
  retval_area[0] = t1;
  retval_area[1] = t2;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */

/* begin module */
/* c_function_name, AF__current__directory */
/* clu_operation_name, _current_directory */
int AF__current__directory(LVdrive)
     object LVdrive;
{
  /* begin body */
  if (OMbool_Dnot(OMstring_Dempty(LVdrive)))
    {
      signame = SLBAD_FORMAT;
      return(SIG);
    }
  if (AF__external__getcwd() == SIG)
    {
      goto except1;
    }
  retval_area[0] = retval_area[0];
  return RET;
  if (FALSE)
    {
    except1:
      if (OMstring_Dequal(signame, SLNOT_POSSIBLE))
        {
	  return(SIG);
        }
      else
        {
	  goto except0;
        }
    }
  /* end body */
  noretval(SLNULL);
  return(SIG);
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */

/* begin module */
/* c_function_name, AF__directory__with__drive */
/* clu_operation_name, _directory_with_drive */
int AF__directory__with__drive(LVdir)
     object LVdir;
{
  /* begin body */
  retval_area[0] = FALSE;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */

/* begin module */
/* c_function_name, AF__is__atomic__directory */
/* clu_operation_name, _is_atomic_directory */
int AF__is__atomic__directory(LVdir)
     object LVdir;
{
  int t1;
  /* begin body */
  if (OMstring_Dempty(LVdir))
    {
      t1 = TRUE;
    }
  else
    {
      t1 = OMstring_Dequal(LVdir, ((string) &str1));
    }
  retval_area[0] = t1;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */

/* begin module */
/* c_function_name, AF__is__path__delimiter */
/* clu_operation_name, _is_path_delimiter */
int AF__is__path__delimiter(LVc)
     object LVc;
{
  /* begin body */
  retval_area[0] = OMchar_Dequal(LVc, '/');
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */

/* begin module */
/* c_function_name, AF__null__device__name */
/* clu_operation_name, _null_device_name */
int AF__null__device__name()
{
  /* begin body */
  if (OFfile__name_Dcreate(((string) &str2), ((string) &str3), SLNULL, SLNULL) == SIG)
    {
      goto except0;
    }
  retval_area[0] = retval_area[0];
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */

/* begin module */
/* c_function_name, AF__path__delimiter */
/* clu_operation_name, _path_delimiter */
int AF__path__delimiter()
{
  /* begin body */
  retval_area[0] = '/';
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */
