/* Generated by clu2c (version 1.99.3) */
/* option, optimize time */
/* depend,_check_directory_entry*/
/* depend,_current_directory,_external_getdcwd*/
/* depend,_directory_with_drive*/
/* depend,_is_atomic_directory,_directory_with_drive,_is_path_delimiter*/
/* depend,_is_path_delimiter*/
/* depend,_null_device_name,file_name*/
/* depend,_path_delimiter*/

#include <clu2c.h>

static STRING_REP(1) str1 = {1, {'.'}};
static STRING_REP(2) str2 = {2, {'.', '.'}};
static STRING_REP(4) str3 = {4, {'~', 'C', 'L', 'U'}};
static STRING_REP(3) str4 = {3, {'n', 'u', 'l'}};

/* begin module */
/* c_function_name, AF__check__directory__entry */
/* clu_operation_name, _check_directory_entry */
int AF__check__directory__entry(LVname, LVsuffix)
     object LVname;
     object LVsuffix;
{
  static bool IV = FALSE;
  static object WVbuf= 0;
  object LVchanged= 0;
  int t1, t2, t3, t4, t5, t6, t7;
  if (IV == FALSE)
    {
      IV = TRUE;
      OFarray_Dnew();
      WVbuf = retval_area[0];
    }
  /* begin body */
  t1 = FALSE;
  if (OMstring_Dequal(LVname, ((string) &str1)))
    {
      t2 = TRUE;
    }
  else
    {
      t2 = OMstring_Dequal(LVname, ((string) &str2));
    }
  if (t2)
    {
      if (OMstring_Dempty(LVsuffix))
        {
	  t1 = TRUE;
        }
    }
  if (t1)
    {
      t3 = LVname;
      t4 = LVsuffix;
      retval_area[0] = t3;
      retval_area[1] = t4;
      return RET;
    }
  OFstring_Dindexc('.', LVname);
  if (OMint_Dgt(retval_area[0], 0))
    {
      t2 = TRUE;
    }
  else
    {
      OFstring_Dindexc(':', LVname);
      t2 = OMint_Dgt(retval_area[0], 0);
    }
  if (t2)
    {
      t1 = TRUE;
    }
  else
    {
      OFstring_Dindexc(':', LVsuffix);
      t1 = OMint_Dgt(retval_area[0], 0);
    }
  if (t1)
    {
      signame = SLBAD_FORMAT;
      return(SIG);
    }
  if (OMint_Dgt(OMstring_Dsize(LVname), 8))
    {
      if (OFstring_Dsubstr(LVname, 1, 8) == SIG)
        {
	  goto except0;
        }
      LVname = retval_area[0];
    }
  if (OMint_Dgt(OMstring_Dsize(LVsuffix), 3))
    {
      if (OFstring_Dsubstr(LVsuffix, 1, 3) == SIG)
        {
	  goto except0;
        }
      LVsuffix = retval_area[0];
    }
  t1 = FALSE;
  if (OMstring_Dequal(LVname, ((string) &str3)))
    {
      if (OMstring_Dempty(LVsuffix))
        {
	  t1 = TRUE;
        }
    }
  if (t1)
    {
      t2 = LVname;
      t3 = LVsuffix;
      retval_area[0] = t2;
      retval_area[1] = t3;
      return RET;
    }
  if (OFarray_Dtrim(WVbuf, 1, 0) == SIG)
    {
      goto except0;
    }
  LVchanged = FALSE;
    {
      object LVc= 0;
      for (t1 = LVname, t2 = 1, t3 = OMstring_Dsize(t1);
           t2 <= t3;
           t2++)
        {
	  LVc = OMstring_Dfetch(t1, t2);
	    {
	      t4 = OMchar_Dle('A', LVc);
	      if (OMbool_Dand(t4, OMchar_Dle(LVc, 'Z')))
	        {
		  t5 = OMchar_Dc2i('a');
		  t6 = OMint_Dsub(t5, OMchar_Dc2i('A'));
		  t7 = OMint_Dadd(t6, OMchar_Dc2i(LVc));
		  if (OMchar_Dillegal__char(t7))
		    {
		      signame = SLILLEGAL_CHAR;
		      goto except0;
		    }
		  LVc = OMchar_Di2c(t7);
		  LVchanged = TRUE;
	        }
	      OMarray_Daddh(WVbuf, LVc);
	    }
        }
    }
  if (LVchanged)
    {
      OFstring_Dac2s(WVbuf);
      LVname = retval_area[0];
    }
  if (OFarray_Dtrim(WVbuf, 1, 0) == SIG)
    {
      goto except0;
    }
  LVchanged = FALSE;
    {
      object LVc= 0;
      for (t1 = LVsuffix, t2 = 1, t3 = OMstring_Dsize(t1);
           t2 <= t3;
           t2++)
        {
	  LVc = OMstring_Dfetch(t1, t2);
	    {
	      t4 = OMchar_Dle('A', LVc);
	      if (OMbool_Dand(t4, OMchar_Dle(LVc, 'Z')))
	        {
		  t5 = OMchar_Dc2i('a');
		  t6 = OMint_Dsub(t5, OMchar_Dc2i('A'));
		  t7 = OMint_Dadd(t6, OMchar_Dc2i(LVc));
		  if (OMchar_Dillegal__char(t7))
		    {
		      signame = SLILLEGAL_CHAR;
		      goto except0;
		    }
		  LVc = OMchar_Di2c(t7);
		  LVchanged = TRUE;
	        }
	      OMarray_Daddh(WVbuf, LVc);
	    }
        }
    }
  if (LVchanged)
    {
      OFstring_Dac2s(WVbuf);
      LVsuffix = retval_area[0];
    }
  t1 = LVname;
  t2 = LVsuffix;
  retval_area[0] = t1;
  retval_area[1] = t2;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */

/* begin module */
/* c_function_name, AF__current__directory */
/* clu_operation_name, _current_directory */
int AF__current__directory(LVdrive)
     object LVdrive;
{
  object LVnum= 0;
  int t1, t2, t3, t4;
  /* begin body */
  if (OMstring_Dempty(LVdrive))
    {
      LVnum = 0;
    }
  else
    {
      if (OMbool_Dnot(OMint_Dequal(OMstring_Dsize(LVdrive), 2)))
        {
	  t1 = TRUE;
        }
      else
        {
	  if (OMstring_Dbounds(LVdrive, 2))
	    {
	      signame = SLBOUNDS;
	      goto except0;
	    }
	  t1 = OMbool_Dnot(OMchar_Dequal(OMstring_Dfetch(LVdrive, 2), ':'));
        }
      if (t1)
        {
	  signame = SLBAD_FORMAT;
	  return(SIG);
        }
      else
        {
	  object LVc= 0;
	  if (OMstring_Dbounds(LVdrive, 1))
	    {
	      signame = SLBOUNDS;
	      goto except0;
	    }
	  LVc = OMstring_Dfetch(LVdrive, 1);
	  t2 = OMchar_Dle('A', LVc);
	  if (OMbool_Dand(t2, OMchar_Dle(LVc, 'Z')))
	    {
	      t3 = OMchar_Dc2i(LVc);
	      LVnum = OMint_Dadd(OMint_Dsub(t3, OMchar_Dc2i('A')), 1);
	    }
	  else
	    {
	      t3 = OMchar_Dle('a', LVc);
	      if (OMbool_Dand(t3, OMchar_Dle(LVc, 'z')))
	        {
		  t4 = OMchar_Dc2i(LVc);
		  LVnum = OMint_Dadd(OMint_Dsub(t4, OMchar_Dc2i('a')), 1);
	        }
	      else
	        {
		  signame = SLBAD_FORMAT;
		  return(SIG);
	        }
	    }
        }
    }
  if (AF__external__getdcwd(LVnum) == SIG)
    {
      goto except1;
    }
  retval_area[0] = retval_area[0];
  return RET;
  if (FALSE)
    {
    except1:
      if (OMstring_Dequal(signame, SLNOT_POSSIBLE))
        {
	  return(SIG);
        }
      else
        {
	  goto except0;
        }
    }
  /* end body */
  noretval(SLNULL);
  return(SIG);
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */

/* begin module */
/* c_function_name, AF__directory__with__drive */
/* clu_operation_name, _directory_with_drive */
int AF__directory__with__drive(LVdir)
     object LVdir;
{
  object LVres= 0;
  int t1, t2, t3, t4;
  /* begin body */
    {
      object LVc= 0;
      if (OMstring_Dbounds(LVdir, 1))
        {
	  signame = SLBOUNDS;
	  goto except1;
        }
      LVc = OMstring_Dfetch(LVdir, 1);
      t1 = FALSE;
      t3 = OMchar_Dle('A', LVc);
      if (OMbool_Dand(t3, OMchar_Dle(LVc, 'Z')))
        {
	  t2 = TRUE;
        }
      else
        {
	  t4 = OMchar_Dle('a', LVc);
	  t2 = OMbool_Dand(t4, OMchar_Dle(LVc, 'z'));
        }
      if (t2)
        {
	  if (OMstring_Dbounds(LVdir, 2))
	    {
	      signame = SLBOUNDS;
	      goto except1;
	    }
	  if (OMchar_Dequal(OMstring_Dfetch(LVdir, 2), ':'))
	    {
	      t1 = TRUE;
	    }
        }
      LVres = t1;
    }
  if (FALSE)
    {
    except1:
      if (OMstring_Dequal(signame, SLBOUNDS))
        {
	  LVres = FALSE;
        }
      else
        {
	  goto except0;
        }
    }
  retval_area[0] = LVres;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */

/* begin module */
/* c_function_name, AF__is__atomic__directory */
/* clu_operation_name, _is_atomic_directory */
int AF__is__atomic__directory(LVdir)
     object LVdir;
{
  object LVi= 0;
  object LVsize= 0;
  int t1, t2;
  /* begin body */
  if (AF__directory__with__drive(LVdir) == SIG)
    {
      goto except0;
    }
  if (retval_area[0])
    {
      LVi = 3;
    }
  else
    {
      LVi = 1;
    }
  LVsize = OMstring_Dsize(LVdir);
  if (OMint_Dgt(LVi, LVsize))
    {
      t1 = TRUE;
    }
  else
    {
      t2 = FALSE;
      if (OMint_Dequal(LVi, LVsize))
        {
	  if (OMstring_Dbounds(LVdir, LVi))
	    {
	      signame = SLBOUNDS;
	      goto except0;
	    }
	  if (AF__is__path__delimiter(OMstring_Dfetch(LVdir, LVi)) == SIG)
	    {
	      goto except0;
	    }
	  if (retval_area[0])
	    {
	      t2 = TRUE;
	    }
        }
      t1 = t2;
    }
  retval_area[0] = t1;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */

/* begin module */
/* c_function_name, AF__is__path__delimiter */
/* clu_operation_name, _is_path_delimiter */
int AF__is__path__delimiter(LVc)
     object LVc;
{
  int t1;
  /* begin body */
  t1 = OMchar_Dequal(LVc, '/');
  retval_area[0] = OMbool_Dor(t1, OMchar_Dequal(LVc, '\\'));
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */

/* begin module */
/* c_function_name, AF__null__device__name */
/* clu_operation_name, _null_device_name */
int AF__null__device__name()
{
  /* begin body */
  if (OFfile__name_Dcreate(SLNULL, ((string) &str4), SLNULL, SLNULL) == SIG)
    {
      goto except0;
    }
  retval_area[0] = retval_area[0];
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */

/* begin module */
/* c_function_name, AF__path__delimiter */
/* clu_operation_name, _path_delimiter */
int AF__path__delimiter()
{
  /* begin body */
  retval_area[0] = '\\';
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */
