/* Generated by clu2c (version 1.99.3) */
/* option, optimize time */
/* depend,current_directory,_current_directory,file_name*/

#include <clu2c.h>

/* begin module */
/* c_function_name, AFcurrent__directory */
/* clu_operation_name, current_directory */
int AFcurrent__directory()
{
  /* begin body */
  if (AF__current__directory(SLNULL) == SIG)
    {
      goto except0;
    }
  if (OFfile__name_Dcreate(retval_area[0], SLNULL, SLNULL, SLNULL) == SIG)
    {
      goto except0;
    }
  retval_area[0] = retval_area[0];
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */
