/* Generated by clu2c (version 1.99.3) */
/* option, optimize time */
/* depend,directory_entry_names,_external_dir,file_name,file_name_to_string*/

#include <clu2c.h>

/* begin module */
/* c_function_name, AFdirectory__entry__names */
/* clu_operation_name, directory_entry_names */
#define INV_TOP 5
#define WORK_SIZE 8
int AFdirectory__entry__names(init, ivarp, LVdir)
     bool init;
     int **ivarp;
     object LVdir;
{
  if (init)
    {
      *ivarp = (int*) malloc(WORK_SIZE*sizeof(int));
      (*ivarp)[1] = LVdir;
    }
  else
    {
      switch ((*ivarp)[0])
  	{
  	  case 1: goto yield1;
  	}
    }
  /* begin body */
  if (AFfile__name__to__string((*ivarp)[1]) == SIG)
    {
      goto except1;
    }
  if (OF__external__dir_Dopen(retval_area[0]) == SIG)
    {
      goto except1;
    }
  (*ivarp)[2] = retval_area[0];
  if (FALSE)
    {
    except1:
      if (OMstring_Dequal(signame, SLNOT_POSSIBLE))
        {
	  return(SIG);
        }
      else
        {
	  goto except0;
        }
    }
  OFarray_Dnew();
  (*ivarp)[3] = retval_area[0];
  while (TRUE)
    {
        {
	  if (OF__external__dir_Dread((*ivarp)[2]) == SIG)
	    {
	      goto except2;
	    }
	  OMarray_Daddh((*ivarp)[3], retval_area[0]);
        }
    }
  if (FALSE)
    {
    except2:
      if (OMstring_Dequal(signame, SLEND_OF_FILE))
        {
        }
      else
        {
	  goto except0;
        }
    }
  if (OF__external__dir_Dclose((*ivarp)[2]) == SIG)
    {
      goto except0;
    }
    {
      for ((*ivarp)[INV_TOP+0] = (*ivarp)[3], (*ivarp)[INV_TOP+1] = OMarray_Dlow((*ivarp)[INV_TOP+0]), (*ivarp)[INV_TOP+2] = OMarray_Dhigh((*ivarp)[INV_TOP+0]);
           (*ivarp)[INV_TOP+1] <= (*ivarp)[INV_TOP+2];
           (*ivarp)[INV_TOP+1]++)
        {
	  (*ivarp)[4] = OMarray_Dfetch((*ivarp)[INV_TOP+0], (*ivarp)[INV_TOP+1]);
	    {
	      retval_area[0] = (*ivarp)[4];
	      (*ivarp)[0] = 1;
	      return YIELD;
	    yield1:
	      NO_OPERATION;
	    }
        }
    }
  /* end body */
  return(RET);
except0:
  out_handler(SLNULL);
  return(SIG);
}
#undef INV_TOP
#undef WORK_SIZE
/* end module */
