/* Generated by clu2c (version 1.99.3) */
/* option, optimize time */
/* depend,directory_file_name,file_name*/

#include <clu2c.h>

/* begin module */
/* c_function_name, AFdirectory__file__name */
/* clu_operation_name, directory_file_name */
int AFdirectory__file__name(LVfn)
     object LVfn;
{
  /* begin body */
  if (OFfile__name_Dget__name(LVfn) == SIG)
    {
      goto except0;
    }
  if (OMbool_Dnot(OMstring_Dempty(retval_area[0])))
    {
      retval_area[0] = LVfn;
      return RET;
    }
  if (OFfile__name_Dget__dir(LVfn) == SIG)
    {
      goto except0;
    }
  if (OFfile__name_Dparse(retval_area[0]) == SIG)
    {
      goto except0;
    }
  retval_area[0] = retval_area[0];
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */
