/* Generated by clu2c (version 1.99.3) */
/* option, optimize time */
/* depend,file_exists,_external_errname,_external_stat,file_name,file_name_to_string*/

#include <clu2c.h>

static STRING_REP(6) str1 = {6, {'E', 'N', 'O', 'E', 'N', 'T'}};
static STRING_REP(7) str2 = {7, {'E', 'N', 'O', 'T', 'D', 'I', 'R'}};

/* begin module */
/* c_function_name, AFfile__exists */
/* clu_operation_name, file_exists */
int AFfile__exists(LVfn)
     object LVfn;
{
  int t1;
  /* begin body */
    {
      if (AFfile__name__to__string(LVfn) == SIG)
        {
	  goto except1;
        }
      if (AF__external__stat(retval_area[0]) == SIG)
        {
	  goto except1;
        }
      retval_area[0] = TRUE;
      return RET;
    }
  if (FALSE)
    {
    except1:
      if (OMstring_Dequal(signame, SLNOT_POSSIBLE))
        {
	  object LVwhy= 0;
	  LVwhy = sigarg_area[0];
	    {
	      object LVerror= 0;
	      if (AF__external__errname() == SIG)
	        {
		  goto except0;
	        }
	      LVerror = retval_area[0];
	      t1 = OMstring_Dequal(LVerror, ((string) &str1));
	      if (OMbool_Dor(t1, OMstring_Dequal(LVerror, ((string) &str2))))
	        {
		  retval_area[0] = FALSE;
		  return RET;
	        }
	      else
	        {
		  sigarg_area[0] = LVwhy;
		  signame = SLNOT_POSSIBLE;
		  return(SIG);
	        }
	    }
        }
      else
        {
	  goto except0;
        }
    }
  /* end body */
  noretval(SLNULL);
  return(SIG);
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */
