/* Generated by clu2c (version 1.99.3) */
/* option, optimize time */
/* depend,file_name_apply_directory,_path_delimiter,file_name,file_name_as_directory,file_name_drive,file_name_is_absolute,file_name_proper_directory*/

#include <clu2c.h>

/* begin module */
/* c_function_name, AFfile__name__apply__directory */
/* clu_operation_name, file_name_apply_directory */
int AFfile__name__apply__directory(LVfn, LVbase)
     object LVfn;
     object LVbase;
{
  object LVdrive= 0;
  object LVbasedir= 0;
  object LVdir= 0;
  int t1, t2;
  /* begin body */
  if (AFfile__name__is__absolute(LVfn) == SIG)
    {
      goto except0;
    }
  if (retval_area[0])
    {
      retval_area[0] = LVfn;
      return RET;
    }
  if (AFfile__name__drive(LVfn) == SIG)
    {
      goto except0;
    }
  if (OMstring_Dempty(retval_area[0]))
    {
      if (AFfile__name__drive(LVbase) == SIG)
        {
	  goto except0;
        }
      LVdrive = retval_area[0];
    }
  else
    {
      if (AFfile__name__drive(LVbase) == SIG)
        {
	  goto except0;
        }
      if (OMstring_Dempty(retval_area[0]))
        {
	  t1 = TRUE;
        }
      else
        {
	  if (AFfile__name__drive(LVfn) == SIG)
	    {
	      goto except0;
	    }
	  t2 = retval_area[0];
	  if (AFfile__name__drive(LVbase) == SIG)
	    {
	      goto except0;
	    }
	  t1 = OMstring_Dequal(t2, retval_area[0]);
        }
      if (t1)
        {
	  if (AFfile__name__drive(LVfn) == SIG)
	    {
	      goto except0;
	    }
	  LVdrive = retval_area[0];
        }
      else
        {
	  retval_area[0] = LVfn;
	  return RET;
        }
    }
  if (AFfile__name__as__directory(LVbase) == SIG)
    {
      goto except0;
    }
  if (AFfile__name__proper__directory(retval_area[0]) == SIG)
    {
      goto except0;
    }
  LVbasedir = retval_area[0];
  if (AFfile__name__proper__directory(LVfn) == SIG)
    {
      goto except0;
    }
  LVdir = retval_area[0];
  if (OMstring_Dempty(LVdir))
    {
      LVdir = LVbasedir;
    }
  else
    {
      if (OMbool_Dnot(OMstring_Dempty(LVbasedir)))
        {
	  if (AF__path__delimiter() == SIG)
	    {
	      goto except0;
	    }
	  OFstring_Dappend(LVbasedir, retval_area[0]);
	  t1 = OMstring_Dsize(retval_area[0])
	       + OMstring_Dsize(LVdir);
	  t2 = OFstring_D__predict(t1);
	  OFstring_D__concat(t2, retval_area[0]);
	  OFstring_D__concat(t2, LVdir);
	  LVdir = t2;
        }
    }
  if (OMbool_Dnot(OMstring_Dempty(LVdrive)))
    {
      t1 = OMstring_Dsize(LVdrive)
           + OMstring_Dsize(LVdir);
      t2 = OFstring_D__predict(t1);
      OFstring_D__concat(t2, LVdrive);
      OFstring_D__concat(t2, LVdir);
      LVdir = t2;
    }
  if (OFfile__name_Dget__name(LVfn) == SIG)
    {
      goto except0;
    }
  t1 = retval_area[0];
  if (OFfile__name_Dget__suffix(LVfn) == SIG)
    {
      goto except0;
    }
  t2 = retval_area[0];
  if (OFfile__name_Dget__other(LVfn) == SIG)
    {
      goto except0;
    }
  if (OFfile__name_Dcreate(LVdir, t1, t2, retval_area[0]) == SIG)
    {
      goto except0;
    }
  retval_area[0] = retval_area[0];
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */
