/* Generated by clu2c (version 1.99.3) */
/* option, optimize time */
/* depend,file_name_as_directory,file_name*/

#include <clu2c.h>

/* begin module */
/* c_function_name, AFfile__name__as__directory */
/* clu_operation_name, file_name_as_directory */
int AFfile__name__as__directory(LVfn)
     object LVfn;
{
  /* begin body */
  if (OFfile__name_Dget__name(LVfn) == SIG)
    {
      goto except0;
    }
  if (OMstring_Dempty(retval_area[0]))
    {
      retval_area[0] = LVfn;
      return RET;
    }
  if (OFfile__name_Dunparse(LVfn) == SIG)
    {
      goto except0;
    }
  if (OFfile__name_Dcreate(retval_area[0], SLNULL, SLNULL, SLNULL) == SIG)
    {
      goto except0;
    }
  retval_area[0] = retval_area[0];
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */
