/* Generated by clu2c (version 1.99.3) */
/* option, optimize time */
/* depend,file_name_absolutize,_current_directory,file_name,file_name_apply_directory,file_name_drive*/

#include <clu2c.h>

/* begin module */
/* c_function_name, AFfile__name__absolutize */
/* clu_operation_name, file_name_absolutize */
int AFfile__name__absolutize(LVfn)
     object LVfn;
{
  object LVcurdir= 0;
  /* begin body */
  if (AFfile__name__drive(LVfn) == SIG)
    {
      goto except0;
    }
  if (AF__current__directory(retval_area[0]) == SIG)
    {
      goto except0;
    }
  LVcurdir = retval_area[0];
  if (OFfile__name_Dcreate(LVcurdir, SLNULL, SLNULL, SLNULL) == SIG)
    {
      goto except0;
    }
  if (AFfile__name__apply__directory(LVfn, retval_area[0]) == SIG)
    {
      goto except0;
    }
  retval_area[0] = retval_area[0];
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */
