/* Generated by clu2c (version 1.99.3) */
/* option, optimize time */
/* depend,file_name_drive,_directory_with_drive,file_name*/

#include <clu2c.h>

/* begin module */
/* c_function_name, AFfile__name__drive */
/* clu_operation_name, file_name_drive */
int AFfile__name__drive(LVfn)
     object LVfn;
{
  object LVdrive= 0;
  object LVdir= 0;
  /* begin body */
  LVdrive = SLNULL;
  if (OFfile__name_Dget__dir(LVfn) == SIG)
    {
      goto except0;
    }
  LVdir = retval_area[0];
  if (AF__directory__with__drive(LVdir) == SIG)
    {
      goto except0;
    }
  if (retval_area[0])
    {
      if (OFstring_Dsubstr(LVdir, 1, 2) == SIG)
        {
	  goto except0;
        }
      LVdrive = retval_area[0];
    }
  retval_area[0] = LVdrive;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */
