/* Generated by clu2c (version 1.99.3) */
/* option, optimize time */
/* depend,file_name_fill_directory,file_name,file_name_absolutize,file_name_apply_directory,file_name_expand_home_directory,working_dir*/

#include <clu2c.h>

/* begin module */
/* c_function_name, AFfile__name__fill__directory */
/* clu_operation_name, file_name_fill_directory */
int AFfile__name__fill__directory(LVfn)
     object LVfn;
{
  /* begin body */
  if (AFworking__dir() == SIG)
    {
      goto except0;
    }
  if (OFfile__name_Dparse(retval_area[0]) == SIG)
    {
      goto except0;
    }
  if (AFfile__name__apply__directory(LVfn, retval_area[0]) == SIG)
    {
      goto except0;
    }
  LVfn = retval_area[0];
  if (AFfile__name__expand__home__directory(LVfn) == SIG)
    {
      goto except0;
    }
  LVfn = retval_area[0];
  if (AFfile__name__absolutize(LVfn) == SIG)
    {
      goto except0;
    }
  retval_area[0] = retval_area[0];
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */
