/* Generated by clu2c (version 1.99.3) */
/* option, optimize time */
/* depend,file_name_fill_suffix,file_name*/

#include <clu2c.h>

/* begin module */
/* c_function_name, AFfile__name__fill__suffix */
/* clu_operation_name, file_name_fill_suffix */
int AFfile__name__fill__suffix(LVfn, LVsuffix)
     object LVfn;
     object LVsuffix;
{
  int t1, t2, t3;
  /* begin body */
  t1 = FALSE;
  if (OFfile__name_Dget__suffix(LVfn) == SIG)
    {
      goto except0;
    }
  if (OMstring_Dempty(retval_area[0]))
    {
      if (OMbool_Dnot(OMstring_Dempty(LVsuffix)))
        {
	  t1 = TRUE;
        }
    }
  if (t1)
    {
      if (OFfile__name_Dget__dir(LVfn) == SIG)
        {
	  goto except1;
        }
      t2 = retval_area[0];
      if (OFfile__name_Dget__name(LVfn) == SIG)
        {
	  goto except1;
        }
      t3 = retval_area[0];
      if (OFfile__name_Dget__other(LVfn) == SIG)
        {
	  goto except1;
        }
      if (OFfile__name_Dcreate(t2, t3, LVsuffix, retval_area[0]) == SIG)
        {
	  goto except1;
        }
      LVfn = retval_area[0];
      if (FALSE)
        {
	except1:
	  if (OMstring_Dequal(signame, SLBAD_FORMAT))
	    {
	    }
	  else
	    {
	      goto except0;
	    }
        }
    }
  retval_area[0] = LVfn;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */
