/* Generated by clu2c (version 1.99.3) */
/* option, optimize time */
/* depend,file_name_is_absolute,_is_path_delimiter,file_name,file_name_proper_directory*/

#include <clu2c.h>

/* begin module */
/* c_function_name, AFfile__name__is__absolute */
/* clu_operation_name, file_name_is_absolute */
int AFfile__name__is__absolute(LVfn)
     object LVfn;
{
  int t1;
  /* begin body */
  if (AFfile__name__proper__directory(LVfn) == SIG)
    {
      goto except1;
    }
  if (OMstring_Dbounds(retval_area[0], 1))
    {
      signame = SLBOUNDS;
      goto except1;
    }
  if (AF__is__path__delimiter(OMstring_Dfetch(retval_area[0], 1)) == SIG)
    {
      goto except1;
    }
  if (retval_area[0])
    {
      t1 = TRUE;
    }
  else
    {
      if (OFfile__name_Dget__dir(LVfn) == SIG)
        {
	  goto except1;
        }
      if (OMstring_Dbounds(retval_area[0], 1))
        {
	  signame = SLBOUNDS;
	  goto except1;
        }
      t1 = OMchar_Dequal(OMstring_Dfetch(retval_area[0], 1), '~');
    }
  retval_area[0] = t1;
  return RET;
  if (FALSE)
    {
    except1:
      if (OMstring_Dequal(signame, SLBOUNDS))
        {
        }
      else
        {
	  goto except0;
        }
    }
  retval_area[0] = FALSE;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */
