/* Generated by clu2c (version 1.99.3) */
/* option, optimize time */
/* depend,file_name_proper_directory,_directory_with_drive,file_name*/

#include <clu2c.h>

/* begin module */
/* c_function_name, AFfile__name__proper__directory */
/* clu_operation_name, file_name_proper_directory */
int AFfile__name__proper__directory(LVfn)
     object LVfn;
{
  object LVdir= 0;
  /* begin body */
  if (OFfile__name_Dget__dir(LVfn) == SIG)
    {
      goto except0;
    }
  LVdir = retval_area[0];
  if (AF__directory__with__drive(LVdir) == SIG)
    {
      goto except0;
    }
  if (retval_area[0])
    {
      if (OFstring_Drest(LVdir, 3) == SIG)
        {
	  goto except0;
        }
      LVdir = retval_area[0];
    }
  retval_area[0] = LVdir;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */
