/* Generated by clu2c (version 1.99.3) */
/* option, optimize time */
/* depend,file_name_simplify,_is_atomic_directory,file_name,file_name_nondirectory*/

#include <clu2c.h>

static STRING_REP(1) str1 = {1, {'.'}};
static STRING_REP(2) str2 = {2, {'.', '.'}};

/* begin module */
/* c_function_name, AFfile__name__simplify */
/* clu_operation_name, file_name_simplify */
int AFfile__name__simplify(LVfn)
     object LVfn;
{
  object LVdir= 0;
  object LVentry= 0;
  int t1, t2, t3;
  /* begin body */
  if (OFfile__name_Dget__dir(LVfn) == SIG)
    {
      goto except0;
    }
  LVdir = retval_area[0];
  if (AF__is__atomic__directory(LVdir) == SIG)
    {
      goto except0;
    }
  if (OMbool_Dnot(retval_area[0]))
    {
      if (OFfile__name_Dparse(LVdir) == SIG)
        {
	  goto except0;
        }
      if (AFfile__name__simplify(retval_area[0]) == SIG)
        {
	  goto except0;
        }
      if (OFfile__name_Dunparse(retval_area[0]) == SIG)
        {
	  goto except0;
        }
      LVdir = retval_area[0];
    }
  if (AFfile__name__nondirectory(LVfn) == SIG)
    {
      goto except0;
    }
  LVentry = retval_area[0];
  if (OMstring_Dequal(LVentry, ((string) &str1)))
    {
      if (OFfile__name_Dparse(LVdir) == SIG)
        {
	  goto except0;
        }
      LVfn = retval_area[0];
    }
  else
    {
      t1 = FALSE;
      if (OMstring_Dequal(LVentry, ((string) &str2)))
        {
	  if (OMbool_Dnot(OMstring_Dempty(LVdir)))
	    {
	      t1 = TRUE;
	    }
        }
      if (t1)
        {
	  object LVdirfn= 0;
	  object LVparent= 0;
	  if (OFfile__name_Dparse(LVdir) == SIG)
	    {
	      goto except0;
	    }
	  LVdirfn = retval_area[0];
	  if (AFfile__name__nondirectory(LVdirfn) == SIG)
	    {
	      goto except0;
	    }
	  LVparent = retval_area[0];
	  if (AF__is__atomic__directory(LVdir) == SIG)
	    {
	      goto except0;
	    }
	  if (retval_area[0])
	    {
	      t2 = TRUE;
	    }
	  else
	    {
	      t2 = OMbool_Dnot(OMstring_Dequal(LVparent, ((string) &str2)));
	    }
	  if (t2)
	    {
	      if (OFfile__name_Dget__dir(LVdirfn) == SIG)
	        {
		  goto except0;
	        }
	      if (OFfile__name_Dparse(retval_area[0]) == SIG)
	        {
		  goto except0;
	        }
	      LVfn = retval_area[0];
	    }
        }
      else
        {
	  if (OFfile__name_Dget__dir(LVfn) == SIG)
	    {
	      goto except0;
	    }
	  if (OMbool_Dnot(OMstring_Dequal(LVdir, retval_area[0])))
	    {
	      if (OFfile__name_Dget__name(LVfn) == SIG)
	        {
		  goto except0;
	        }
	      t2 = retval_area[0];
	      if (OFfile__name_Dget__suffix(LVfn) == SIG)
	        {
		  goto except0;
	        }
	      t3 = retval_area[0];
	      if (OFfile__name_Dget__other(LVfn) == SIG)
	        {
		  goto except0;
	        }
	      if (OFfile__name_Dcreate(LVdir, t2, t3, retval_area[0]) == SIG)
	        {
		  goto except0;
	        }
	      LVfn = retval_area[0];
	    }
        }
    }
  retval_area[0] = LVfn;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */
