/* Generated by clu2c (version 1.99.3) */
/* option, optimize time */
/* depend,file_name_to_string,directory_file_name,file_name,file_name_apply_directory,file_name_expand_home_directory,file_name_is_absolute,working_dir*/

#include <clu2c.h>

static STRING_REP(1) str1 = {1, {'.'}};

/* begin module */
/* c_function_name, AFfile__name__to__string */
/* clu_operation_name, file_name_to_string */
int AFfile__name__to__string(LVfn)
     object LVfn;
{
  object LVs= 0;
  /* begin body */
  if (AFfile__name__is__absolute(LVfn) == SIG)
    {
      goto except0;
    }
  if (OMbool_Dnot(retval_area[0]))
    {
      if (AFworking__dir() == SIG)
        {
	  goto except0;
        }
      if (OFfile__name_Dparse(retval_area[0]) == SIG)
        {
	  goto except0;
        }
      if (AFfile__name__apply__directory(LVfn, retval_area[0]) == SIG)
        {
	  goto except0;
        }
      LVfn = retval_area[0];
    }
  if (AFdirectory__file__name(LVfn) == SIG)
    {
      goto except0;
    }
  LVfn = retval_area[0];
  if (AFfile__name__expand__home__directory(LVfn) == SIG)
    {
      goto except0;
    }
  LVfn = retval_area[0];
  if (OFfile__name_Dunparse(LVfn) == SIG)
    {
      goto except0;
    }
  LVs = retval_area[0];
  if (OMstring_Dempty(LVs))
    {
      LVs = ((string) &str1);
    }
  retval_area[0] = LVs;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */
