/* Generated by clu2c (version 1.99.3) */
/* option, optimize time */
/* depend,file_name_expand_home_directory,_is_path_delimiter,directory_file_name,file_name,file_name_apply_directory,home_directory*/

#include <clu2c.h>

/* begin module */
/* c_function_name, AFfile__name__expand__home__directory */
/* clu_operation_name, file_name_expand_home_directory */
int AFfile__name__expand__home__directory(LVfn)
     object LVfn;
{
  object LVuser= 0;
  object LVhome= 0;
  int t1, t2;
  /* begin body */
  if (OFfile__name_Dget__dir(LVfn) == SIG)
    {
      goto except1;
    }
  if (OMstring_Dbounds(retval_area[0], 1))
    {
      signame = SLBOUNDS;
      goto except1;
    }
  if (OMbool_Dnot(OMchar_Dequal(OMstring_Dfetch(retval_area[0], 1), '~')))
    {
      retval_area[0] = LVfn;
      return RET;
    }
  else
    {
      object LVi= 0;
      object LVuser= 0;
      object LVhome= 0;
      object LVrestdir= 0;
      LVi = 2;
      while (TRUE)
        {
	  if (OFfile__name_Dget__dir(LVfn) == SIG)
	    {
	      goto except2;
	    }
	  if (OMstring_Dbounds(retval_area[0], LVi))
	    {
	      signame = SLBOUNDS;
	      goto except2;
	    }
	  if (AF__is__path__delimiter(OMstring_Dfetch(retval_area[0], LVi)) == SIG)
	    {
	      goto except2;
	    }
	  if (!OMbool_Dnot(retval_area[0]))
	    {
	      break;
	    }
	    {
	      LVi = OMint_Dadd(LVi, 1);
	    }
        }
      if (FALSE)
        {
	except2:
	  if (OMstring_Dequal(signame, SLBOUNDS))
	    {
	    }
	  else
	    {
	      goto except1;
	    }
        }
      if (OFfile__name_Dget__dir(LVfn) == SIG)
        {
	  goto except1;
        }
      t1 = retval_area[0];
      if (OFstring_Dsubstr(t1, 2, OMint_Dsub(LVi, 2)) == SIG)
        {
	  goto except1;
        }
      LVuser = retval_area[0];
      if (AFhome__directory(LVuser) == SIG)
        {
	  goto except3;
        }
      LVhome = retval_area[0];
      if (FALSE)
        {
	except3:
	  if (OMstring_Dequal(signame, SLNOT_FOUND))
	    {
	      retval_area[0] = LVfn;
	      return RET;
	    }
	  else
	    {
	      goto except1;
	    }
        }
      if (OFfile__name_Dget__dir(LVfn) == SIG)
        {
	  goto except1;
        }
      if (OMint_Dgt(LVi, OMstring_Dsize(retval_area[0])))
        {
	  LVrestdir = SLNULL;
        }
      else
        {
	  if (OFfile__name_Dget__dir(LVfn) == SIG)
	    {
	      goto except1;
	    }
	  t1 = retval_area[0];
	  if (OFstring_Drest(t1, OMint_Dadd(LVi, 1)) == SIG)
	    {
	      goto except1;
	    }
	  LVrestdir = retval_area[0];
        }
      if (OFfile__name_Dget__name(LVfn) == SIG)
        {
	  goto except1;
        }
      t1 = retval_area[0];
      if (OFfile__name_Dget__suffix(LVfn) == SIG)
        {
	  goto except1;
        }
      t2 = retval_area[0];
      if (OFfile__name_Dget__other(LVfn) == SIG)
        {
	  goto except1;
        }
      if (OFfile__name_Dcreate(LVrestdir, t1, t2, retval_area[0]) == SIG)
        {
	  goto except1;
        }
      LVfn = retval_area[0];
      if (AFfile__name__apply__directory(LVfn, LVhome) == SIG)
        {
	  goto except1;
        }
      retval_area[0] = retval_area[0];
      return RET;
    }
  if (FALSE)
    {
    except1:
      if (OMstring_Dequal(signame, SLBOUNDS))
        {
        }
      else
        {
	  goto except0;
        }
    }
  if (OFfile__name_Dget__name(LVfn) == SIG)
    {
      goto except0;
    }
  if (OMstring_Dempty(retval_area[0]))
    {
      t1 = TRUE;
    }
  else
    {
      if (OFfile__name_Dget__name(LVfn) == SIG)
        {
	  goto except0;
        }
      if (OMstring_Dbounds(retval_area[0], 1))
        {
	  signame = SLBOUNDS;
	  goto except0;
        }
      t1 = OMbool_Dnot(OMchar_Dequal(OMstring_Dfetch(retval_area[0], 1), '~'));
    }
  if (t1)
    {
      retval_area[0] = LVfn;
      return RET;
    }
  if (OFfile__name_Dunparse(LVfn) == SIG)
    {
      goto except0;
    }
  if (OFstring_Drest(retval_area[0], 2) == SIG)
    {
      goto except0;
    }
  LVuser = retval_area[0];
  if (AFhome__directory(LVuser) == SIG)
    {
      goto except4;
    }
  LVhome = retval_area[0];
  if (FALSE)
    {
    except4:
      if (OMstring_Dequal(signame, SLNOT_FOUND))
        {
	  retval_area[0] = LVfn;
	  return RET;
        }
      else
        {
	  goto except0;
        }
    }
  if (AFdirectory__file__name(LVhome) == SIG)
    {
      goto except0;
    }
  retval_area[0] = retval_area[0];
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */
