/* Generated by clu2c (version 1.99.3) */
/* option, optimize time */
/* depend,input_streams,file_name,program_name,stream*/

#include <clu2c.h>

static STRING_REP(1) str1 = {1, {'-'}};
static STRING_REP(4) str2 = {4, {'r', 'e', 'a', 'd'}};
static STRING_REP(2) str3 = {2, {':', ' '}};
static STRING_REP(22) str4 = {22, {':', ' ', 'b', 'a', 'd', ' ', 'f', 'o', 'r', 'm', 'a', 't', ' ', 'f', 'i', 'l', 'e', ' ', 'n', 'a', 'm', 'e'}};

/* begin module */
/* c_function_name, AFinput__streams */
/* clu_operation_name, input_streams */
#define INV_TOP 6
#define WORK_SIZE 9
int AFinput__streams(init, ivarp, LVinputs)
     bool init;
     int **ivarp;
     object LVinputs;
{
  if (init)
    {
      *ivarp = (int*) malloc(WORK_SIZE*sizeof(int));
      (*ivarp)[1] = LVinputs;
    }
  else
    {
      switch ((*ivarp)[0])
  	{
  	  case 1: goto yield1;
  	  case 2: goto yield2;
  	  case 3: goto yield3;
  	}
    }
  /* begin body */
  if (OMsequence_Dempty((*ivarp)[1]))
    {
      if (OFstream_Dprimary__input() == SIG)
        {
	  goto except0;
        }
      retval_area[0] = retval_area[0];
      (*ivarp)[0] = 1;
      return YIELD;
    yield1:
      NO_OPERATION;
      return RET;
    }
  if (OFstream_Derror__output() == SIG)
    {
      goto except0;
    }
  (*ivarp)[2] = retval_area[0];
    {
      for ((*ivarp)[INV_TOP+0] = (*ivarp)[1], (*ivarp)[INV_TOP+1] = 1, (*ivarp)[INV_TOP+2] = OMsequence_Dsize((*ivarp)[INV_TOP+0]);
           (*ivarp)[INV_TOP+1] <= (*ivarp)[INV_TOP+2];
           (*ivarp)[INV_TOP+1]++)
        {
	  (*ivarp)[3] = OMsequence_Dfetch((*ivarp)[INV_TOP+0], (*ivarp)[INV_TOP+1]);
	    {
	      if (OMstring_Dequal((*ivarp)[3], ((string) &str1)))
	        {
		  if (OFstream_Dprimary__input() == SIG)
		    {
		      goto except1;
		    }
		  retval_area[0] = retval_area[0];
		  (*ivarp)[0] = 2;
		  return YIELD;
		yield2:
		  NO_OPERATION;
	        }
	      else
	        {
		  if (OFfile__name_Dparse((*ivarp)[3]) == SIG)
		    {
		      goto except1;
		    }
		  (*ivarp)[4] = retval_area[0];
		  if (OFstream_Dopen((*ivarp)[4], ((string) &str2)) == SIG)
		    {
		      goto except1;
		    }
		  (*ivarp)[5] = retval_area[0];
		  retval_area[0] = (*ivarp)[5];
		  (*ivarp)[0] = 3;
		  return YIELD;
		yield3:
		  NO_OPERATION;
		  if (OFstream_Dclose((*ivarp)[5]) == SIG)
		    {
		      goto except2;
		    }
		  if (FALSE)
		    {
		    except2:
		      if (OMstring_Dequal(signame, SLNOT_POSSIBLE))
		        {
		        }
		      else
		        {
			  goto except1;
		        }
		    }
	        }
	      if (FALSE)
	        {
		except1:
		  if (OMstring_Dequal(signame, SLBAD_FORMAT))
		    {
		      if (AFprogram__name() == SIG)
		        {
			  goto except0;
		        }
		      if (OFstream_Dputs((*ivarp)[2], retval_area[0]) == SIG)
		        {
			  goto except0;
		        }
		      if (OFstream_Dputs((*ivarp)[2], ((string) &str3)) == SIG)
		        {
			  goto except0;
		        }
		      if (OFstream_Dputs((*ivarp)[2], (*ivarp)[3]) == SIG)
		        {
			  goto except0;
		        }
		      if (OFstream_Dputl((*ivarp)[2], ((string) &str4)) == SIG)
		        {
			  goto except0;
		        }
		    }
		  else if (OMstring_Dequal(signame, SLNOT_POSSIBLE))
		    {
		      (*ivarp)[5] = sigarg_area[0];
		        {
			  if (AFprogram__name() == SIG)
			    {
			      goto except0;
			    }
			  if (OFstream_Dputs((*ivarp)[2], retval_area[0]) == SIG)
			    {
			      goto except0;
			    }
			  if (OFstream_Dputs((*ivarp)[2], ((string) &str3)) == SIG)
			    {
			      goto except0;
			    }
			  if (OFfile__name_Dunparse((*ivarp)[4]) == SIG)
			    {
			      goto except0;
			    }
			  if (OFstream_Dputs((*ivarp)[2], retval_area[0]) == SIG)
			    {
			      goto except0;
			    }
			  if (OFstream_Dputs((*ivarp)[2], ((string) &str3)) == SIG)
			    {
			      goto except0;
			    }
			  if (OFstream_Dputl((*ivarp)[2], (*ivarp)[5]) == SIG)
			    {
			      goto except0;
			    }
		        }
		    }
		  else
		    {
		      goto except0;
		    }
	        }
	    }
        }
    }
  /* end body */
  return(RET);
except0:
  out_handler(SLNULL);
  return(SIG);
}
#undef INV_TOP
#undef WORK_SIZE
/* end module */
