/* Generated by clu2c (version 1.99.3) */
/* option, optimize time */
/* depend,int_oct_unparse*/

#include <clu2c.h>

static STRING_REP(1) str1 = {1, {'0'}};

/* begin module */
/* c_function_name, AFint__oct__unparse */
/* clu_operation_name, int_oct_unparse */
int AFint__oct__unparse(LVi)
     object LVi;
{
  object LVbuffer= 0;
  int t1, t2;
  /* begin body */
  if (OMint_Dequal(LVi, 0))
    {
      retval_area[0] = ((string) &str1);
      return RET;
    }
  OFarray_Dnew();
  LVbuffer = retval_area[0];
  if (OMint_Dgt(LVi, 0))
    {
      while (TRUE)
        {
	  if (!OMint_Dgt(LVi, 0))
	    {
	      break;
	    }
	    {
	      t1 = OMchar_Dc2i('0');
	      if (OMint_Dzero__divide(8))
	        {
		  signame = SLZERO_DIVIDE;
		  goto except0;
	        }
	      t2 = OMint_Dadd(t1, OMint_Dmod(LVi, 8));
	      if (OMchar_Dillegal__char(t2))
	        {
		  signame = SLILLEGAL_CHAR;
		  goto except0;
	        }
	      OMarray_Daddl(LVbuffer, OMchar_Di2c(t2));
	      if (OMint_Dzero__divide(8))
	        {
		  signame = SLZERO_DIVIDE;
		  goto except0;
	        }
	      LVi = OMint_Ddiv(LVi, 8);
	    }
        }
    }
  else
    {
      while (TRUE)
        {
	  if (!OMint_Dlt(LVi, 0))
	    {
	      break;
	    }
	    {
	      object LVr= 0;
	      object LVd= 0;
	      object LVa= 0;
	      if (OMint_Dzero__divide(8))
	        {
		  signame = SLZERO_DIVIDE;
		  goto except0;
	        }
	      LVr = OMint_Dmod(LVi, 8);
	      LVd = LVr;
	      LVa = 0;
	      if (OMint_Dgt(LVr, 0))
	        {
		  LVd = OMint_Dsub(8, LVr);
		  LVa = 1;
	        }
	      t1 = OMint_Dadd(OMchar_Dc2i('0'), LVd);
	      if (OMchar_Dillegal__char(t1))
	        {
		  signame = SLILLEGAL_CHAR;
		  goto except0;
	        }
	      OMarray_Daddl(LVbuffer, OMchar_Di2c(t1));
	      if (OMint_Dzero__divide(8))
	        {
		  signame = SLZERO_DIVIDE;
		  goto except0;
	        }
	      LVi = OMint_Dadd(OMint_Ddiv(LVi, 8), LVa);
	    }
        }
      OMarray_Daddl(LVbuffer, '-');
    }
  OFstring_Dac2s(LVbuffer);
  retval_area[0] = retval_area[0];
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */
