/* Generated by clu2c (version 1.99.3) */
/* option, optimize time */
/* depend,int_hex_unparse*/

#include <clu2c.h>

static STRING_REP(1) str1 = {1, {'0'}};
static STRING_REP(16) str2 = {16, {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f'}};

/* begin module */
/* c_function_name, AFint__hex__unparse */
/* clu_operation_name, int_hex_unparse */
int AFint__hex__unparse(LVi)
     object LVi;
{
  object LVbuffer= 0;
  int t1;
  /* begin body */
  if (OMint_Dequal(LVi, 0))
    {
      retval_area[0] = ((string) &str1);
      return RET;
    }
  OFarray_Dnew();
  LVbuffer = retval_area[0];
  if (OMint_Dgt(LVi, 0))
    {
      while (TRUE)
        {
	  if (!OMint_Dgt(LVi, 0))
	    {
	      break;
	    }
	    {
	      if (OMint_Dzero__divide(16))
	        {
		  signame = SLZERO_DIVIDE;
		  goto except0;
	        }
	      t1 = OMint_Dadd(OMint_Dmod(LVi, 16), 1);
	      if (OMstring_Dbounds(((string) &str2), t1))
	        {
		  signame = SLBOUNDS;
		  goto except0;
	        }
	      OMarray_Daddl(LVbuffer, OMstring_Dfetch(((string) &str2), t1));
	      if (OMint_Dzero__divide(16))
	        {
		  signame = SLZERO_DIVIDE;
		  goto except0;
	        }
	      LVi = OMint_Ddiv(LVi, 16);
	    }
        }
    }
  else
    {
      while (TRUE)
        {
	  if (!OMint_Dlt(LVi, 0))
	    {
	      break;
	    }
	    {
	      object LVr= 0;
	      object LVd= 0;
	      object LVa= 0;
	      if (OMint_Dzero__divide(16))
	        {
		  signame = SLZERO_DIVIDE;
		  goto except0;
	        }
	      LVr = OMint_Dmod(LVi, 16);
	      LVd = LVr;
	      LVa = 0;
	      if (OMint_Dgt(LVr, 0))
	        {
		  LVd = OMint_Dsub(16, LVr);
		  LVa = 1;
	        }
	      t1 = OMint_Dadd(LVd, 1);
	      if (OMstring_Dbounds(((string) &str2), t1))
	        {
		  signame = SLBOUNDS;
		  goto except0;
	        }
	      OMarray_Daddl(LVbuffer, OMstring_Dfetch(((string) &str2), t1));
	      if (OMint_Dzero__divide(16))
	        {
		  signame = SLZERO_DIVIDE;
		  goto except0;
	        }
	      LVi = OMint_Dadd(OMint_Ddiv(LVi, 16), LVa);
	    }
        }
      OMarray_Daddl(LVbuffer, '-');
    }
  OFstring_Dac2s(LVbuffer);
  retval_area[0] = retval_area[0];
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */
