/* Generated by clu2c (version 1.99.3) */
/* option, optimize time */
/* depend,int_hex_parse*/

#include <clu2c.h>

/* begin module */
/* c_function_name, AFint__hex__parse */
/* clu_operation_name, int_hex_parse */
int AFint__hex__parse(LVs)
     object LVs;
{
  object LVstart= 0;
  object LVsign= 0;
  object LVc= 0;
  object LVvalue= 0;
  int t1, t2, t3, t4, t5, t6;
  /* begin body */
  LVstart = 1;
  LVsign = 1;
  if (OMstring_Dbounds(LVs, 1))
    {
      signame = SLBOUNDS;
      goto except1;
    }
  LVc = OMstring_Dfetch(LVs, 1);
  if (FALSE)
    {
    except1:
      if (OMstring_Dequal(signame, SLBOUNDS))
        {
	  signame = SLBAD_FORMAT;
	  return(SIG);
        }
      else
        {
	  goto except0;
        }
    }
  t1 = OMchar_Dequal(LVc, '+');
  if (OMbool_Dor(t1, OMchar_Dequal(LVc, '-')))
    {
      LVstart = 2;
      if (OMint_Dlt(OMstring_Dsize(LVs), 2))
        {
	  signame = SLBAD_FORMAT;
	  return(SIG);
        }
      if (OMchar_Dequal(LVc, '-'))
        {
	  LVsign = -1;
        }
    }
  LVvalue = 0;
    {
      object LVi= 0;
      for (t1 = LVstart, t2 = OMstring_Dsize(LVs); t1 <= t2; t1++)
        {
	  LVi = t1;
	    {
	      object LVdigit= 0;
	      if (OMstring_Dbounds(LVs, LVi))
	        {
		  signame = SLBOUNDS;
		  goto except0;
	        }
	      LVc = OMstring_Dfetch(LVs, LVi);
	      t3 = OMchar_Dge(LVc, '0');
	      if (OMbool_Dand(t3, OMchar_Dle(LVc, '9')))
	        {
		  t4 = OMchar_Dc2i(LVc);
		  LVdigit = OMint_Dsub(t4, OMchar_Dc2i('0'));
	        }
	      else
	        {
		  t4 = OMchar_Dge(LVc, 'a');
		  if (OMbool_Dand(t4, OMchar_Dle(LVc, 'f')))
		    {
		      t5 = OMchar_Dc2i(LVc);
		      LVdigit = OMint_Dadd(OMint_Dsub(t5, OMchar_Dc2i('a')), 10);
		    }
		  else
		    {
		      t5 = OMchar_Dge(LVc, 'A');
		      if (OMbool_Dand(t5, OMchar_Dle(LVc, 'F')))
		        {
			  t6 = OMchar_Dc2i(LVc);
			  LVdigit = OMint_Dadd(OMint_Dsub(t6, OMchar_Dc2i('A')), 10);
		        }
		      else
		        {
			  signame = SLBAD_FORMAT;
			  return(SIG);
		        }
		    }
	        }
	      t3 = OMint_Dmul(LVvalue, 16);
	      LVvalue = OMint_Dadd(t3, OMint_Dmul(LVsign, LVdigit));
	      if (FALSE)
	        {
		except2:
		  if (OMstring_Dequal(signame, SLOVERFLOW))
		    {
		      return(SIG);
		    }
		  else
		    {
		      goto except0;
		    }
	        }
	    }
        }
    }
  retval_area[0] = LVvalue;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */
