/* Generated by clu2c (version 1.99.3) */
/* option, optimize time */
/* depend,program_name,rt_env*/

#include <clu2c.h>

/* begin module */
/* c_function_name, AFprogram__name */
/* clu_operation_name, program_name */
int AFprogram__name()
{
  /* begin body */
  if (OFrt__env_Done() == SIG)
    {
      goto except0;
    }
  if (OFrt__env_Dget__program__name(retval_area[0]) == SIG)
    {
      goto except0;
    }
  retval_area[0] = retval_area[0];
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */
