/* Generated by clu2c (version 1.99.3) */
/* option, optimize time */
/* depend,pstream,file_name,stream*/

#include <clu2c.h>

static STRING_REP(14) str1 = {14, {'i', 'l', 'l', 'e', 'g', 'a', 'l', '_', 's', 't', 'r', 'e', 'a', 'm'}};
static STRING_REP(3) str2 = {3, {'.', '.', '.'}};
static STRING_REP(1) str3 = {1, {' '}};
static STRING_REP(8) str4 = {8, {'p', 's', 't', 'r', 'e', 'a', 'm', '['}};
static STRING_REP(2) str5 = {2, {'d', ' '}};
static STRING_REP(4) str6 = {4, {'w', ' ', 'f', ' '}};
static STRING_REP(4) str7 = {4, {'w', ' ', 'i', ' '}};
static STRING_REP(2) str8 = {2, {'m', ' '}};
static STRING_REP(2) str9 = {2, {'s', ' '}};
static STRING_REP(10) str10 = {10, {'(', 'i', 'n', 't', 'e', 'r', 'n', 'a', 'l', ')'}};

/* begin module */
/* c_function_name, OFpstream_Dprimary__output */
/* clu_operation_name, pstream$primary_output */
int OFpstream_Dprimary__output()
{
  static bool IV = FALSE;
  static object WVpo= 0;
  if (IV == FALSE)
    {
      IV = TRUE;
      if (OFstream_Dprimary__output() == SIG)
        {
	  goto except0;
        }
      if (OFpstream_Dcreate(retval_area[0], 4, 4) == SIG)
        {
	  goto except0;
        }
      WVpo = retval_area[0];
    }
  /* begin body */
  retval_area[0] = WVpo;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFpstream_Dcreate */
/* clu_operation_name, pstream$create */
int OFpstream_Dcreate(LVst, LVmax__depth, LVmax__width)
     object LVst;
     object LVmax__depth;
     object LVmax__width;
{
  object LVps= 0;
  int t1, t2;
  /* begin body */
  if (OFstream_Dcan__write(LVst) == SIG)
    {
      goto except0;
    }
  if (OMbool_Dnot(retval_area[0]))
    {
      signame = ((string) &str1);
      return(SIG);
    }
  OFarray_Dnew();
  t1 = retval_area[0];
  OFarray_Dnew();
  t2 = OFrecord_D__alloc(12);
  OMrecord_Dset(1, t2, FALSE);
  OMrecord_Dset(2, t2, retval_area[0]);
  OMrecord_Dset(3, t2, t1);
  OMrecord_Dset(4, t2, 0);
  OMrecord_Dset(5, t2, FALSE);
  OMrecord_Dset(6, t2, 0);
  OMrecord_Dset(7, t2, 1073741823);
  OMrecord_Dset(8, t2, LVmax__depth);
  OMrecord_Dset(9, t2, LVmax__width);
  OMrecord_Dset(10, t2, 0);
  OMrecord_Dset(11, t2, LVst);
  OMrecord_Dset(12, t2, TRUE);
  LVps = t2;
  if (OFstream_Dget__line__length(LVst) == SIG)
    {
      goto except1;
    }
  OMrecord_Dset(7, LVps, retval_area[0]);
  if (FALSE)
    {
    except1:
      if (OMstring_Dequal(signame, SLNO_LIMIT))
        {
	  OMrecord_Dset(12, LVps, FALSE);
        }
      else
        {
	  goto except0;
        }
    }
  retval_area[0] = LVps;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFpstream_Dget__depth */
/* clu_operation_name, pstream$get_depth */
int OFpstream_Dget__depth(LVx)
     object LVx;
{
  /* begin body */
  retval_area[0] = OMrecord_Dget(4, LVx);
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFpstream_Dget__hpos */
/* clu_operation_name, pstream$get_hpos */
int OFpstream_Dget__hpos(LVx)
     object LVx;
{
  /* begin body */
  retval_area[0] = OMrecord_Dget(6, LVx);
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFpstream_Dstart */
/* clu_operation_name, pstream$start */
int OFpstream_Dstart(LVps, LVs)
     object LVps;
     object LVs;
{
  object LVdepth= 0;
  int t1;
  /* begin body */
  LVdepth = OMint_Dadd(OMrecord_Dget(4, LVps), 1);
  OMrecord_Dset(4, LVps, LVdepth);
  if (OMrecord_Dget(1, LVps))
    {
      retval_area[0] = FALSE;
      return RET;
    }
  if (OFpstream_Dputs(LVps, LVs) == SIG)
    {
      goto except0;
    }
  OMarray_Daddh(OMrecord_Dget(3, LVps), 0);
  t1 = OMrecord_Dget(2, LVps);
  OMarray_Daddh(t1, OMrecord_Dget(6, LVps));
  if (OMint_Dgt(LVdepth, OMrecord_Dget(8, LVps)))
    {
      if (OFpstream_Dputs(LVps, ((string) &str2)) == SIG)
        {
	  goto except0;
        }
      OMrecord_Dset(1, LVps, TRUE);
      retval_area[0] = FALSE;
      return RET;
    }
  retval_area[0] = TRUE;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFpstream_Dstop */
/* clu_operation_name, pstream$stop */
int OFpstream_Dstop(LVps, LVs)
     object LVps;
     object LVs;
{
  object LVdepth= 0;
  int t1;
  /* begin body */
  LVdepth = OMint_Dsub(OMrecord_Dget(4, LVps), 1);
  OMrecord_Dset(4, LVps, LVdepth);
  if (OMint_Dge(LVdepth, OMarray_Dsize(OMrecord_Dget(2, LVps))))
    {
      retval_area[0] = FALSE;
      return RET;
    }
  t1 = OMrecord_Dget(2, LVps);
  if (OMarray_Dempty(t1))
    {
      signame = SLBOUNDS;
      goto except0;
    }
  OMarray_Dremh(t1);
  t1 = OMrecord_Dget(3, LVps);
  if (OMarray_Dempty(t1))
    {
      signame = SLBOUNDS;
      goto except0;
    }
  OMarray_Dremh(t1);
  OMrecord_Dset(1, LVps, FALSE);
  if (OFpstream_Dputs(LVps, LVs) == SIG)
    {
      goto except0;
    }
  retval_area[0] = TRUE;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFpstream_Dpause */
/* clu_operation_name, pstream$pause */
int OFpstream_Dpause(LVps, LVs)
     object LVps;
     object LVs;
{
  object LVdepth= 0;
  object LVwidth= 0;
  int t1;
  /* begin body */
  if (OMrecord_Dget(1, LVps))
    {
      retval_area[0] = FALSE;
      return RET;
    }
  LVdepth = OMrecord_Dget(4, LVps);
  if (OFpstream_Dputs(LVps, LVs) == SIG)
    {
      goto except0;
    }
  if (OMint_Dequal(LVdepth, 0))
    {
      if (OFstream_Dputc(OMrecord_Dget(11, LVps), '\n') == SIG)
        {
	  goto except0;
        }
      OMrecord_Dset(6, LVps, 0);
      OMrecord_Dset(10, LVps, 0);
      retval_area[0] = TRUE;
      return RET;
    }
  if (OMrecord_Dget(5, LVps))
    {
      if (OFpstream_Dputs(LVps, ((string) &str3)) == SIG)
        {
	  goto except0;
        }
    }
  else
    {
      if (OFstream_Dputc(OMrecord_Dget(11, LVps), '\n') == SIG)
        {
	  goto except0;
        }
      OMrecord_Dset(6, LVps, 0);
      OMrecord_Dset(10, LVps, 0);
      t1 = OMrecord_Dget(2, LVps);
      if (OMarray_Dempty(t1))
        {
	  signame = SLBOUNDS;
	  goto except0;
        }
      if (OFpstream_Dputsp(LVps, OMarray_Dtop(t1)) == SIG)
        {
	  goto except0;
        }
    }
  t1 = OMrecord_Dget(3, LVps);
  if (OMarray_Dempty(t1))
    {
      signame = SLBOUNDS;
      goto except0;
    }
  LVwidth = OMint_Dadd(OMarray_Dtop(t1), 1);
  t1 = OMrecord_Dget(3, LVps);
  if (OMarray_Dbounds(t1, LVdepth))
    {
      signame = SLBOUNDS;
      goto except0;
    }
  OMarray_Dstore(t1, LVdepth, LVwidth);
  if (OMint_Dge(LVwidth, OMrecord_Dget(9, LVps)))
    {
      if (OFpstream_Dputs(LVps, ((string) &str2)) == SIG)
        {
	  goto except0;
        }
      OMrecord_Dset(1, LVps, TRUE);
      retval_area[0] = FALSE;
      return RET;
    }
  retval_area[0] = TRUE;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFpstream_Dtext */
/* clu_operation_name, pstream$text */
int OFpstream_Dtext(LVps, LVs)
     object LVps;
     object LVs;
{
  /* begin body */
  if (OMrecord_Dget(1, LVps))
    {
      retval_area[0] = FALSE;
      return RET;
    }
  if (OFpstream_Dputs(LVps, LVs) == SIG)
    {
      goto except0;
    }
  retval_area[0] = TRUE;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFpstream_Dtextc */
/* clu_operation_name, pstream$textc */
int OFpstream_Dtextc(LVps, LVc)
     object LVps;
     object LVc;
{
  int t1, t2, t3;
  /* begin body */
  if (OMrecord_Dget(1, LVps))
    {
      retval_area[0] = FALSE;
      return RET;
    }
  if (OMchar_Dequal(LVc, '\n'))
    {
      if (OFstream_Dputc(OMrecord_Dget(11, LVps), LVc) == SIG)
        {
	  goto except0;
        }
      OMrecord_Dset(6, LVps, 0);
      OMrecord_Dset(10, LVps, 0);
    }
  else
    {
      OMrecord_Dset(6, LVps, OMint_Dadd(OMrecord_Dget(6, LVps), 1));
      if (OMrecord_Dget(12, LVps))
        {
	  t1 = TRUE;
        }
      else
        {
	  t2 = OMrecord_Dget(10, LVps);
	  t1 = OMint_Dlt(t2, OMrecord_Dget(7, LVps));
        }
      if (t1)
        {
	  t3 = OMrecord_Dget(10, LVps);
	  if (OMint_Dge(t3, OMrecord_Dget(7, LVps)))
	    {
	      if (OFstream_Dputc(OMrecord_Dget(11, LVps), '\n') == SIG)
	        {
		  goto except0;
	        }
	      OMrecord_Dset(10, LVps, 0);
	    }
	  OMrecord_Dset(10, LVps, OMint_Dadd(OMrecord_Dget(10, LVps), 1));
	  if (OFstream_Dputc(OMrecord_Dget(11, LVps), LVc) == SIG)
	    {
	      goto except0;
	    }
        }
    }
  retval_area[0] = TRUE;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFpstream_Dputleft */
/* clu_operation_name, pstream$putleft */
int OFpstream_Dputleft(LVps, LVs, LVsize)
     object LVps;
     object LVs;
     object LVsize;
{
  object LVdiff= 0;
  object LVb= 0;
  /* begin body */
  if (OMint_Dlt(LVsize, 0))
    {
      signame = SLNEGATIVE_FIELD_WIDTH;
      return(SIG);
    }
  LVdiff = OMint_Dsub(LVsize, OMstring_Dsize(LVs));
  if (OFpstream_Dtext(LVps, LVs) == SIG)
    {
      goto except0;
    }
  LVb = retval_area[0];
  if (OMint_Dgt(LVdiff, 0))
    {
      if (OFpstream_Dputspace(LVps, LVdiff) == SIG)
        {
	  goto except0;
        }
    }
  retval_area[0] = LVb;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFpstream_Dputright */
/* clu_operation_name, pstream$putright */
int OFpstream_Dputright(LVps, LVs, LVsize)
     object LVps;
     object LVs;
     object LVsize;
{
  object LVdiff= 0;
  /* begin body */
  if (OMint_Dlt(LVsize, 0))
    {
      signame = SLNEGATIVE_FIELD_WIDTH;
      return(SIG);
    }
  LVdiff = OMint_Dsub(LVsize, OMstring_Dsize(LVs));
  if (OMint_Dgt(LVdiff, 0))
    {
      if (OFpstream_Dputspace(LVps, LVdiff) == SIG)
        {
	  goto except0;
        }
    }
  if (OFpstream_Dtext(LVps, LVs) == SIG)
    {
      goto except0;
    }
  retval_area[0] = retval_area[0];
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFpstream_Dputspace */
/* clu_operation_name, pstream$putspace */
int OFpstream_Dputspace(LVps, LVlen)
     object LVps;
     object LVlen;
{
  /* begin body */
  if (OMint_Dlt(LVlen, 0))
    {
      signame = SLNEGATIVE_FIELD_WIDTH;
      return(SIG);
    }
  if (OMrecord_Dget(1, LVps))
    {
      retval_area[0] = FALSE;
      return RET;
    }
  if (OFpstream_Dputsp(LVps, LVlen) == SIG)
    {
      goto except0;
    }
  retval_area[0] = TRUE;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFpstream_Dputs */
/* clu_operation_name, pstream$puts */
int OFpstream_Dputs(LVps, LVs)
     object LVps;
     object LVs;
{
  object LVlen= 0;
  int t1, t2, t3, t4, t5;
  /* begin body */
  LVlen = OMstring_Dsize(LVs);
  if (OMint_Dequal(LVlen, 0))
    {
      return RET;
    }
  OMrecord_Dset(6, LVps, OMint_Dadd(OMrecord_Dget(6, LVps), LVlen));
  t1 = FALSE;
  t2 = FALSE;
  if (OMbool_Dnot(OMrecord_Dget(12, LVps)))
    {
      t3 = OMrecord_Dget(10, LVps);
      if (OMint_Dge(t3, OMrecord_Dget(7, LVps)))
        {
	  t2 = TRUE;
        }
    }
  if (t2)
    {
      OFstring_Dindexc('\n', LVs);
      if (OMint_Dequal(retval_area[0], 0))
        {
	  t1 = TRUE;
        }
    }
  if (t1)
    {
      return RET;
    }
  OMrecord_Dset(10, LVps, OMint_Dadd(OMrecord_Dget(10, LVps), LVlen));
  t1 = FALSE;
  t2 = OMrecord_Dget(10, LVps);
  if (OMint_Dle(t2, OMrecord_Dget(7, LVps)))
    {
      OFstring_Dindexc('\n', LVs);
      if (OMint_Dequal(retval_area[0], 0))
        {
	  t1 = TRUE;
        }
    }
  if (t1)
    {
      if (OFstream_Dputs(OMrecord_Dget(11, LVps), LVs) == SIG)
        {
	  goto except0;
        }
      return RET;
    }
  OMrecord_Dset(6, LVps, OMint_Dsub(OMrecord_Dget(6, LVps), LVlen));
  OMrecord_Dset(10, LVps, OMint_Dsub(OMrecord_Dget(10, LVps), LVlen));
    {
      object LVc= 0;
      for (t1 = LVs, t2 = 1, t3 = OMstring_Dsize(t1);
           t2 <= t3;
           t2++)
        {
	  LVc = OMstring_Dfetch(t1, t2);
	    {
	      if (OMchar_Dequal(LVc, '\n'))
	        {
		  if (OFstream_Dputc(OMrecord_Dget(11, LVps), LVc) == SIG)
		    {
		      goto except0;
		    }
		  OMrecord_Dset(6, LVps, 0);
		  OMrecord_Dset(10, LVps, 0);
	        }
	      else
	        {
		  t4 = FALSE;
		  if (OMrecord_Dget(12, LVps))
		    {
		      t5 = OMrecord_Dget(10, LVps);
		      if (OMint_Dge(t5, OMrecord_Dget(7, LVps)))
		        {
			  t4 = TRUE;
		        }
		    }
		  if (t4)
		    {
		      if (OFstream_Dputc(OMrecord_Dget(11, LVps), '\n') == SIG)
		        {
			  goto except0;
		        }
		      OMrecord_Dset(10, LVps, 0);
		    }
		  t4 = OMrecord_Dget(10, LVps);
		  if (OMint_Dlt(t4, OMrecord_Dget(7, LVps)))
		    {
		      if (OFstream_Dputc(OMrecord_Dget(11, LVps), LVc) == SIG)
		        {
			  goto except0;
		        }
		      OMrecord_Dset(10, LVps, OMint_Dadd(OMrecord_Dget(10, LVps), 1));
		    }
		  OMrecord_Dset(6, LVps, OMint_Dadd(OMrecord_Dget(6, LVps), 1));
	        }
	    }
        }
    }
  /* end body */
  return(RET);
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFpstream_Dputsp */
/* clu_operation_name, pstream$putsp */
int OFpstream_Dputsp(LVps, LVlen)
     object LVps;
     object LVlen;
{
  int t1, t2;
  /* begin body */
  if (OMint_Dequal(LVlen, 0))
    {
      return RET;
    }
  OMrecord_Dset(6, LVps, OMint_Dadd(OMrecord_Dget(6, LVps), LVlen));
  t1 = FALSE;
  if (OMbool_Dnot(OMrecord_Dget(12, LVps)))
    {
      t2 = OMrecord_Dget(10, LVps);
      if (OMint_Dge(t2, OMrecord_Dget(7, LVps)))
        {
	  t1 = TRUE;
        }
    }
  if (t1)
    {
      return RET;
    }
  OMrecord_Dset(10, LVps, OMint_Dadd(OMrecord_Dget(10, LVps), LVlen));
  t1 = OMrecord_Dget(10, LVps);
  if (OMint_Dle(t1, OMrecord_Dget(7, LVps)))
    {
      if (OFstream_Dputspace(OMrecord_Dget(11, LVps), LVlen) == SIG)
        {
	  goto except0;
        }
      return RET;
    }
  while (TRUE)
    {
      t1 = OMrecord_Dget(10, LVps);
      if (!OMint_Dgt(t1, OMrecord_Dget(7, LVps)))
        {
	  break;
        }
        {
	  if (OFstream_Dputc(OMrecord_Dget(11, LVps), '\n') == SIG)
	    {
	      goto except0;
	    }
	  t2 = OMrecord_Dget(10, LVps);
	  OMrecord_Dset(10, LVps, OMint_Dsub(t2, OMrecord_Dget(7, LVps)));
        }
    }
  t1 = OMrecord_Dget(11, LVps);
  if (OFstream_Dputspace(t1, OMrecord_Dget(10, LVps)) == SIG)
    {
      goto except0;
    }
  /* end body */
  return(RET);
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFpstream_Dget__indent */
/* clu_operation_name, pstream$get_indent */
int OFpstream_Dget__indent(LVps)
     object LVps;
{
  int t1;
  /* begin body */
  t1 = OMrecord_Dget(2, LVps);
  if (OMarray_Dempty(t1))
    {
      signame = SLBOUNDS;
      goto except1;
    }
  retval_area[0] = OMarray_Dtop(t1);
  return RET;
  if (FALSE)
    {
    except1:
      if (OMstring_Dequal(signame, SLBOUNDS))
        {
	  retval_area[0] = 0;
	  return RET;
        }
      else
        {
	  goto except0;
        }
    }
  /* end body */
  noretval(SLNULL);
  return(SIG);
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFpstream_Dset__indent */
/* clu_operation_name, pstream$set_indent */
int OFpstream_Dset__indent(LVps, LVindent)
     object LVps;
     object LVindent;
{
  int t1, t2;
  /* begin body */
  t1 = OMrecord_Dget(2, LVps);
  t2 = OMrecord_Dget(4, LVps);
  if (OMarray_Dbounds(t1, t2))
    {
      signame = SLBOUNDS;
      goto except1;
    }
  OMarray_Dstore(t1, t2, LVindent);
  if (FALSE)
    {
    except1:
      if (OMstring_Dequal(signame, SLBOUNDS))
        {
        }
      else
        {
	  goto except0;
        }
    }
  /* end body */
  return(RET);
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFpstream_Dget__max__depth */
/* clu_operation_name, pstream$get_max_depth */
int OFpstream_Dget__max__depth(LVps)
     object LVps;
{
  /* begin body */
  retval_area[0] = OMrecord_Dget(8, LVps);
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFpstream_Dset__max__depth */
/* clu_operation_name, pstream$set_max_depth */
int OFpstream_Dset__max__depth(LVps, LVdepth)
     object LVps;
     object LVdepth;
{
  /* begin body */
  OMrecord_Dset(8, LVps, LVdepth);
  /* end body */
  return(RET);
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFpstream_Dget__max__width */
/* clu_operation_name, pstream$get_max_width */
int OFpstream_Dget__max__width(LVps)
     object LVps;
{
  /* begin body */
  retval_area[0] = OMrecord_Dget(9, LVps);
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFpstream_Dset__max__width */
/* clu_operation_name, pstream$set_max_width */
int OFpstream_Dset__max__width(LVps, LVwidth)
     object LVps;
     object LVwidth;
{
  /* begin body */
  OMrecord_Dset(9, LVps, LVwidth);
  /* end body */
  return(RET);
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFpstream_Dget__flat */
/* clu_operation_name, pstream$get_flat */
int OFpstream_Dget__flat(LVps)
     object LVps;
{
  /* begin body */
  retval_area[0] = OMrecord_Dget(5, LVps);
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFpstream_Dset__flat */
/* clu_operation_name, pstream$set_flat */
int OFpstream_Dset__flat(LVps, LVflat)
     object LVps;
     object LVflat;
{
  /* begin body */
  OMrecord_Dset(5, LVps, LVflat);
  /* end body */
  return(RET);
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFpstream_Dget__wrap */
/* clu_operation_name, pstream$get_wrap */
int OFpstream_Dget__wrap(LVps)
     object LVps;
{
  /* begin body */
  retval_area[0] = OMrecord_Dget(12, LVps);
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFpstream_Dset__wrap */
/* clu_operation_name, pstream$set_wrap */
int OFpstream_Dset__wrap(LVps, LVwrap)
     object LVps;
     object LVwrap;
{
  /* begin body */
  OMrecord_Dset(12, LVps, LVwrap);
  /* end body */
  return(RET);
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFpstream_Dget__line__length */
/* clu_operation_name, pstream$get_line_length */
int OFpstream_Dget__line__length(LVps)
     object LVps;
{
  /* begin body */
  if (OFstream_Dget__line__length(OMrecord_Dget(11, LVps)) == SIG)
    {
      goto except1;
    }
  retval_area[0] = retval_area[0];
  return RET;
  if (FALSE)
    {
    except1:
      if (OMstring_Dequal(signame, SLNO_LIMIT))
        {
	  return(SIG);
        }
      else
        {
	  goto except0;
        }
    }
  /* end body */
  noretval(SLNULL);
  return(SIG);
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFpstream_Dget__page__length */
/* clu_operation_name, pstream$get_page_length */
int OFpstream_Dget__page__length(LVps)
     object LVps;
{
  /* begin body */
  if (OFstream_Dget__page__length(OMrecord_Dget(11, LVps)) == SIG)
    {
      goto except1;
    }
  retval_area[0] = retval_area[0];
  return RET;
  if (FALSE)
    {
    except1:
      if (OMstring_Dequal(signame, SLNO_LIMIT))
        {
	  return(SIG);
        }
      else
        {
	  goto except0;
        }
    }
  /* end body */
  noretval(SLNULL);
  return(SIG);
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFpstream_Dequal */
/* clu_operation_name, pstream$equal */
int OFpstream_Dequal(LVx, LVy)
     object LVx;
     object LVy;
{
  /* begin body */
  OFrecord_Dequal(LVx, LVy);
  retval_area[0] = retval_area[0];
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFpstream_Dreset */
/* clu_operation_name, pstream$reset */
int OFpstream_Dreset(LVps)
     object LVps;
{
  /* begin body */
  OMrecord_Dset(6, LVps, 0);
  OMrecord_Dset(10, LVps, 0);
  OMrecord_Dset(1, LVps, FALSE);
  OMrecord_Dset(4, LVps, 0);
  if (OFarray_Dtrim(OMrecord_Dget(2, LVps), 1, 0) == SIG)
    {
      goto except0;
    }
  if (OFarray_Dtrim(OMrecord_Dget(3, LVps), 1, 0) == SIG)
    {
      goto except0;
    }
  /* end body */
  return(RET);
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFpstream_Dprint */
/* clu_operation_name, pstream$print */
int OFpstream_Dprint(LVps1, LVps2)
     object LVps1;
     object LVps2;
{
  /* begin body */
  if (OFpstream_Dtext(LVps2, ((string) &str4)) == SIG)
    {
      goto except0;
    }
  OFint_Dprint(OMrecord_Dget(8, LVps1), LVps2);
  if (OFpstream_Dtext(LVps2, ((string) &str5)) == SIG)
    {
      goto except0;
    }
  OFint_Dprint(OMrecord_Dget(9, LVps1), LVps2);
  if (OMrecord_Dget(5, LVps1))
    {
      if (OFpstream_Dtext(LVps2, ((string) &str6)) == SIG)
        {
	  goto except0;
        }
    }
  else
    {
      if (OFpstream_Dtext(LVps2, ((string) &str7)) == SIG)
        {
	  goto except0;
        }
    }
  if (OMrecord_Dget(12, LVps1))
    {
      if (OFpstream_Dtext(LVps2, ((string) &str8)) == SIG)
        {
	  goto except0;
        }
    }
  else
    {
      if (OFpstream_Dtext(LVps2, ((string) &str9)) == SIG)
        {
	  goto except0;
        }
    }
  if (OFstream_Dget__name(OMrecord_Dget(11, LVps1)) == SIG)
    {
      goto except1;
    }
  if (OFfile__name_Dprint(retval_area[0], LVps2) == SIG)
    {
      goto except1;
    }
  if (FALSE)
    {
    except1:
      if (OMstring_Dequal(signame, SLNOT_POSSIBLE))
        {
	  if (OFpstream_Dtext(LVps2, ((string) &str10)) == SIG)
	    {
	      goto except0;
	    }
        }
      else
        {
	  goto except0;
        }
    }
  if (OFpstream_Dtextc(LVps2, ']') == SIG)
    {
      goto except0;
    }
  /* end body */
  return(RET);
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */
