/* Generated by clu2c (version 1.99.3) */
/* option, optimize time */
/* depend,rt_env,_external_argc,_external_argv,_external_getenv,default_root_directory,file_name,file_name_as_directory*/

#include <clu2c.h>

static bool	IV_IN_Crt__env = FALSE;
static object	WVrte_IN_Crt__env;

static STRING_REP(6) str1 = {6, {'1', '.', '9', '9', '.', '3'}};
static STRING_REP(9) str2 = {9, {'C', 'L', 'U', '2', 'C', 'R', 'O', 'O', 'T'}};

/* begin module */
/* c_function_name, OFrt__env_Dcreate */
/* clu_operation_name, rt_env$create */
int OFrt__env_Dcreate()
{
  int t1, t2;
  if (IV_IN_Crt__env == FALSE)
    {
      IV_IN_Crt__env = TRUE;
      if (IF_IN_Crt__env() == SIG)
        {
	  goto except0;
        }
    }
  /* begin body */
  OFoneof_Dmake(1, NIL);
  t1 = retval_area[0];
  OFoneof_Dmake(1, NIL);
  t2 = OFrecord_D__alloc(2);
  OMrecord_Dset(1, t2, t1);
  OMrecord_Dset(2, t2, retval_area[0]);
  retval_area[0] = t2;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFrt__env_Done */
/* clu_operation_name, rt_env$one */
int OFrt__env_Done()
{
  if (IV_IN_Crt__env == FALSE)
    {
      IV_IN_Crt__env = TRUE;
      if (IF_IN_Crt__env() == SIG)
        {
	  goto except0;
        }
    }
  /* begin body */
  retval_area[0] = WVrte_IN_Crt__env;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFrt__env_Dget__system__version */
/* clu_operation_name, rt_env$get_system_version */
int OFrt__env_Dget__system__version(LVe)
     object LVe;
{
  if (IV_IN_Crt__env == FALSE)
    {
      IV_IN_Crt__env = TRUE;
      if (IF_IN_Crt__env() == SIG)
        {
	  goto except0;
        }
    }
  /* begin body */
  retval_area[0] = ((string) &str1);
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFrt__env_Dget__system__root__directory */
/* clu_operation_name, rt_env$get_system_root_directory */
int OFrt__env_Dget__system__root__directory(LVe)
     object LVe;
{
  int t1, t2;
  if (IV_IN_Crt__env == FALSE)
    {
      IV_IN_Crt__env = TRUE;
      if (IF_IN_Crt__env() == SIG)
        {
	  goto except0;
        }
    }
  /* begin body */
  t1 = OMrecord_Dget(1, LVe);
  t2 = ((oneof) t1)->tag;
  if (t2 == 1)
    {
        {
	  object LVclu2c__root= 0;
	  object LVroot__dir= 0;
	  if (AF__external__getenv(((string) &str2)) == SIG)
	    {
	      goto except1;
	    }
	  LVclu2c__root = retval_area[0];
	  if (FALSE)
	    {
	    except1:
	      if (OMstring_Dequal(signame, SLNOT_FOUND))
	        {
		  if (AFdefault__root__directory() == SIG)
		    {
		      goto except0;
		    }
		  LVclu2c__root = retval_area[0];
	        }
	      else
	        {
		  goto except0;
	        }
	    }
	  if (OFfile__name_Dcreate(LVclu2c__root, SLNULL, SLNULL, SLNULL) == SIG)
	    {
	      goto except0;
	    }
	  LVroot__dir = retval_area[0];
	  OFoneof_Dmake(2, LVroot__dir);
	  OMrecord_Dset(1, LVe, retval_area[0]);
	  retval_area[0] = LVroot__dir;
	  return RET;
        }
    }
  else if (t2 == 2)
    {
      object LVroot__dir= 0;
      LVroot__dir = ((oneof) t1)->value;
        {
	  retval_area[0] = LVroot__dir;
	  return RET;
        }
    }
  /* end body */
  noretval(SLNULL);
  return(SIG);
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFrt__env_Dset__system__root__directory */
/* clu_operation_name, rt_env$set_system_root_directory */
int OFrt__env_Dset__system__root__directory(LVe, LVroot__dir)
     object LVe;
     object LVroot__dir;
{
  if (IV_IN_Crt__env == FALSE)
    {
      IV_IN_Crt__env = TRUE;
      if (IF_IN_Crt__env() == SIG)
        {
	  goto except0;
        }
    }
  /* begin body */
  if (AFfile__name__as__directory(LVroot__dir) == SIG)
    {
      goto except0;
    }
  LVroot__dir = retval_area[0];
  OFoneof_Dmake(2, LVroot__dir);
  OMrecord_Dset(1, LVe, retval_area[0]);
  /* end body */
  return(RET);
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFrt__env_Dget__working__directory */
/* clu_operation_name, rt_env$get_working_directory */
int OFrt__env_Dget__working__directory(LVe)
     object LVe;
{
  int t1, t2;
  if (IV_IN_Crt__env == FALSE)
    {
      IV_IN_Crt__env = TRUE;
      if (IF_IN_Crt__env() == SIG)
        {
	  goto except0;
        }
    }
  /* begin body */
  t1 = OMrecord_Dget(2, LVe);
  t2 = ((oneof) t1)->tag;
  if (t2 == 1)
    {
        {
	  signame = SLUNDEFINED;
	  return(SIG);
        }
    }
  else if (t2 == 2)
    {
      object LVwork__dir= 0;
      LVwork__dir = ((oneof) t1)->value;
        {
	  retval_area[0] = LVwork__dir;
	  return RET;
        }
    }
  /* end body */
  noretval(SLNULL);
  return(SIG);
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFrt__env_Dset__working__directory */
/* clu_operation_name, rt_env$set_working_directory */
int OFrt__env_Dset__working__directory(LVe, LVwork__dir)
     object LVe;
     object LVwork__dir;
{
  if (IV_IN_Crt__env == FALSE)
    {
      IV_IN_Crt__env = TRUE;
      if (IF_IN_Crt__env() == SIG)
        {
	  goto except0;
        }
    }
  /* begin body */
  if (AFfile__name__as__directory(LVwork__dir) == SIG)
    {
      goto except0;
    }
  LVwork__dir = retval_area[0];
  OFoneof_Dmake(2, LVwork__dir);
  OMrecord_Dset(2, LVe, retval_area[0]);
  /* end body */
  return(RET);
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFrt__env_Dunset__working__directory */
/* clu_operation_name, rt_env$unset_working_directory */
int OFrt__env_Dunset__working__directory(LVe)
     object LVe;
{
  if (IV_IN_Crt__env == FALSE)
    {
      IV_IN_Crt__env = TRUE;
      if (IF_IN_Crt__env() == SIG)
        {
	  goto except0;
        }
    }
  /* begin body */
  OFoneof_Dmake(1, NIL);
  OMrecord_Dset(2, LVe, retval_area[0]);
  /* end body */
  return(RET);
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFrt__env_Dget__argument__vector */
/* clu_operation_name, rt_env$get_argument_vector */
int OFrt__env_Dget__argument__vector(LVe)
     object LVe;
{
  object LVres= 0;
  int t1, t2;
  if (IV_IN_Crt__env == FALSE)
    {
      IV_IN_Crt__env = TRUE;
      if (IF_IN_Crt__env() == SIG)
        {
	  goto except0;
        }
    }
  /* begin body */
  OFarray_Dnew();
  LVres = retval_area[0];
    {
      object LVi= 0;
      if (AF__external__argc() == SIG)
        {
	  goto except0;
        }
      for (t1 = 1, t2 = OMint_Dsub(retval_area[0], 1); t1 <= t2; t1++)
        {
	  LVi = t1;
	    {
	      if (AF__external__argv(LVi) == SIG)
	        {
		  goto except0;
	        }
	      OMarray_Daddh(LVres, retval_area[0]);
	    }
        }
    }
  OFsequence_Da2s(LVres);
  retval_area[0] = retval_area[0];
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFrt__env_Dget__program__name */
/* clu_operation_name, rt_env$get_program_name */
int OFrt__env_Dget__program__name(LVe)
     object LVe;
{
  if (IV_IN_Crt__env == FALSE)
    {
      IV_IN_Crt__env = TRUE;
      if (IF_IN_Crt__env() == SIG)
        {
	  goto except0;
        }
    }
  /* begin body */
  if (AF__external__argv(0) == SIG)
    {
      goto except0;
    }
  retval_area[0] = retval_area[0];
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, IF_IN_Crt__env */
/* clu_operation_name, rt_env$#initown */
int IF_IN_Crt__env()
{
  /* begin body */
  if (OFrt__env_Dcreate() == SIG)
    {
      goto except0;
    }
  WVrte_IN_Crt__env = retval_area[0];
  /* end body */
  return(RET);
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */
