/* Generated by clu2c (version 1.99.3) */
/* option, optimize time */
/* depend,split_directory_entry*/

#include <clu2c.h>

/* begin module */
/* c_function_name, AFsplit__directory__entry */
/* clu_operation_name, split_directory_entry */
int AFsplit__directory__entry(LVent)
     object LVent;
{
  object LVname= 0;
  object LVsuffix= 0;
  int t1, t2, t3, t4;
  /* begin body */
  LVname = LVent;
  LVsuffix = SLNULL;
    {
      object LVi= 0;
      for (t1 = OMstring_Dsize(LVent); t1 >= 1; t1 -= 1)
        {
	  LVi = t1;
	    {
	      if (OMstring_Dbounds(LVent, LVi))
	        {
		  signame = SLBOUNDS;
		  goto except0;
	        }
	      if (OMbool_Dnot(OMchar_Dequal(OMstring_Dfetch(LVent, LVi), '.')))
	        {
		  continue;
	        }
	      t2 = FALSE;
	      t3 = OMint_Dsub(LVi, 1);
	      if (OMstring_Dbounds(LVent, t3))
	        {
		  signame = SLBOUNDS;
		  goto except1;
	        }
	      if (OMbool_Dnot(OMchar_Dequal(OMstring_Dfetch(LVent, t3), '.')))
	        {
		  t4 = OMint_Dadd(LVi, 1);
		  if (OMstring_Dbounds(LVent, t4))
		    {
		      signame = SLBOUNDS;
		      goto except1;
		    }
		  if (OMbool_Dnot(OMchar_Dequal(OMstring_Dfetch(LVent, t4), '.')))
		    {
		      t2 = TRUE;
		    }
	        }
	      if (t2)
	        {
		  if (OFstring_Dsubstr(LVent, 1, OMint_Dsub(LVi, 1)) == SIG)
		    {
		      goto except1;
		    }
		  LVname = retval_area[0];
		  if (OFstring_Drest(LVent, OMint_Dadd(LVi, 1)) == SIG)
		    {
		      goto except1;
		    }
		  LVsuffix = retval_area[0];
	        }
	      if (FALSE)
	        {
		except1:
		  if (OMstring_Dequal(signame, SLBOUNDS))
		    {
		    }
		  else
		    {
		      goto except0;
		    }
	        }
	      break;
	    }
        }
    }
  t1 = LVname;
  t2 = LVsuffix;
  retval_area[0] = t1;
  retval_area[1] = t2;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */
