/* Generated by clu2c (version 1.99.3) */
/* option, optimize time */
/* depend,system,_external_system*/

#include <clu2c.h>

/* begin module */
/* c_function_name, AFsystem */
/* clu_operation_name, system */
int AFsystem(LVcommand)
     object LVcommand;
{
  /* begin body */
  if (AF__external__system(LVcommand) == SIG)
    {
      goto except0;
    }
  retval_area[0] = retval_area[0];
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */
