/* Generated by clu2c (version 1.99.3) */
/* option, optimize time */
/* depend,delete_file,_external_errname,_external_unlink,file_name,file_name_to_string*/

#include <clu2c.h>

static STRING_REP(6) str1 = {6, {'E', 'N', 'O', 'E', 'N', 'T'}};

/* begin module */
/* c_function_name, AFdelete__file */
/* clu_operation_name, delete_file */
int AFdelete__file(LVfn)
     object LVfn;
{
  /* begin body */
  if (AFfile__name__to__string(LVfn) == SIG)
    {
      goto except1;
    }
  if (AF__external__unlink(retval_area[0]) == SIG)
    {
      goto except1;
    }
  if (FALSE)
    {
    except1:
      if (OMstring_Dequal(signame, SLNOT_POSSIBLE))
        {
	  object LVwhy= 0;
	  LVwhy = sigarg_area[0];
	    {
	      if (AF__external__errname() == SIG)
	        {
		  goto except0;
	        }
	      if (OMbool_Dnot(OMstring_Dequal(retval_area[0], ((string) &str1))))
	        {
		  sigarg_area[0] = LVwhy;
		  signame = SLNOT_POSSIBLE;
		  return(SIG);
	        }
	    }
        }
      else
        {
	  goto except0;
        }
    }
  /* end body */
  return(RET);
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */
