/* Generated by clu2c (version 1.99.3) */
/* option, optimize time */
/* depend,e_form,_real_round*/
/* depend,_real_round*/

#include <clu2c.h>

static STRING_REP(19) str1 = {19, {'i', 'l', 'l', 'e', 'g', 'a', 'l', '_', 'f', 'i', 'e', 'l', 'd', '_', 'w', 'i', 'd', 't', 'h'}};
static STRING_REP(1) str2 = {1, {'1'}};

/* begin module */
/* c_function_name, AFe__form */
/* clu_operation_name, e_form */
int AFe__form(LVx, LVint__width, LVfrac__width)
     object LVx;
     object LVint__width;
     object LVfrac__width;
{
  static bool IV = FALSE;
  static object WVexp__width= 0;
  object LVmant__width= 0;
  object LVresult= 0;
  object LVdigits= 0;
  object LVexponent= 0;
  object LVexp= 0;
  int t1, t2, t3, t4;
  if (IV == FALSE)
    {
      IV = TRUE;
      if (OFreal_D__exp__width() == SIG)
        {
	  goto except0;
        }
      WVexp__width = retval_area[0];
    }
  /* begin body */
  LVmant__width = OMint_Dadd(LVint__width, LVfrac__width);
  if (OMint_Dlt(LVint__width, 0))
    {
      t2 = TRUE;
    }
  else
    {
      t2 = OMint_Dlt(LVfrac__width, 0);
    }
  if (t2)
    {
      t1 = TRUE;
    }
  else
    {
      t1 = OMint_Dlt(LVmant__width, 1);
    }
  if (t1)
    {
      signame = ((string) &str1);
      return(SIG);
    }
  OFarray_Dnew();
  LVresult = retval_area[0];
  if (OFreal_Dlt(LVx, OFreal_Dlit(0.)) == SIG)
    {
      goto except0;
    }
  if (retval_area[0])
    {
      OMarray_Daddh(LVresult, '-');
      if (OFreal_Dminus(LVx) == SIG)
        {
	  goto except0;
        }
      LVx = retval_area[0];
    }
  if (OFreal_D__unparse(LVx) == SIG)
    {
      goto except0;
    }
  LVdigits = retval_area[0];
  LVexponent = retval_area[1];
  if (AF__real__round(LVdigits, LVexponent, LVmant__width) == SIG)
    {
      goto except0;
    }
  LVdigits = retval_area[0];
  LVexponent = retval_area[1];
    {
      object LVi= 0;
      t1 = OMint_Dsub(LVint__width, 1);
      for (t2 = t1, t3 = OMint_Dminus(LVfrac__width); t2 >= t3; t2 -= 1)
        {
	  LVi = t2;
	    {
	      object LVdigit= 0;
	      if (OMint_Dequal(LVi, -1))
	        {
		  OMarray_Daddh(LVresult, '.');
	        }
	      t4 = OMint_Dsub(LVint__width, LVi);
	      if (OMstring_Dbounds(LVdigits, t4))
	        {
		  signame = SLBOUNDS;
		  goto except1;
	        }
	      LVdigit = OMstring_Dfetch(LVdigits, t4);
	      if (FALSE)
	        {
		except1:
		  if (OMstring_Dequal(signame, SLBOUNDS))
		    {
		      LVdigit = '0';
		    }
		  else
		    {
		      goto except0;
		    }
	        }
	      OMarray_Daddh(LVresult, LVdigit);
	    }
        }
    }
  OMarray_Daddh(LVresult, 'e');
  if (OFreal_Dequal(LVx, OFreal_Dlit(0.)) == SIG)
    {
      goto except0;
    }
  if (OMbool_Dnot(retval_area[0]))
    {
      LVexponent = OMint_Dadd(OMint_Dsub(LVexponent, LVint__width), 1);
    }
  if (OMint_Dlt(LVexponent, 0))
    {
      OMarray_Daddh(LVresult, '-');
      LVexponent = OMint_Dminus(LVexponent);
    }
  else
    {
      OMarray_Daddh(LVresult, '+');
    }
  OFint_Dunparse(LVexponent);
  LVexp = retval_area[0];
    {
      object LVi= 0;
      for (t1 = 1, t2 = OMint_Dsub(WVexp__width, OMstring_Dsize(LVexp)); t1 <= t2; t1++)
        {
	  LVi = t1;
	    {
	      OMarray_Daddh(LVresult, '0');
	    }
        }
    }
    {
      object LVdigit= 0;
      for (t1 = LVexp, t2 = 1, t3 = OMstring_Dsize(t1);
           t2 <= t3;
           t2++)
        {
	  LVdigit = OMstring_Dfetch(t1, t2);
	    {
	      OMarray_Daddh(LVresult, LVdigit);
	    }
        }
    }
  OFstring_Dac2s(LVresult);
  retval_area[0] = retval_area[0];
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */

/* begin module */
/* c_function_name, AF__real__round */
/* clu_operation_name, _real_round */
int AF__real__round(LVdigits, LVexponent, LVwidth)
     object LVdigits;
     object LVexponent;
     object LVwidth;
{
  int t1, t2, t3, t4;
  /* begin body */
  if (OMint_Dlt(LVwidth, 0))
    {
      signame = SLNEGATIVE_FIELD_WIDTH;
      return(SIG);
    }
  else
    {
      if (OMint_Dlt(LVwidth, OMstring_Dsize(LVdigits)))
        {
	  object LVdigit= 0;
	  t1 = OMint_Dadd(LVwidth, 1);
	  if (OMstring_Dbounds(LVdigits, t1))
	    {
	      signame = SLBOUNDS;
	      goto except0;
	    }
	  LVdigit = OMstring_Dfetch(LVdigits, t1);
	  if (OFstring_Dsubstr(LVdigits, 1, LVwidth) == SIG)
	    {
	      goto except0;
	    }
	  LVdigits = retval_area[0];
	  if (OMchar_Dge(LVdigit, '5'))
	    {
	      object LVzeros= 0;
	      LVzeros = SLNULL;
	        {
		  object LVi= 0;
		  LVi = LVwidth;
		  while (TRUE)
		    {
		      if (OMstring_Dbounds(LVdigits, LVi))
		        {
			  signame = SLBOUNDS;
			  goto except1;
		        }
		      if (!OMchar_Dequal(OMstring_Dfetch(LVdigits, LVi), '9'))
		        {
			  break;
		        }
		        {
			  LVi = OMint_Dsub(LVi, 1);
			  OFstring_Dappend(LVzeros, '0');
			  LVzeros = retval_area[0];
		        }
		    }
		  if (OFstring_Dsubstr(LVdigits, 1, OMint_Dsub(LVi, 1)) == SIG)
		    {
		      goto except1;
		    }
		  t1 = retval_area[0];
		  if (OMstring_Dbounds(LVdigits, LVi))
		    {
		      signame = SLBOUNDS;
		      goto except1;
		    }
		  t2 = OMint_Dadd(OMchar_Dc2i(OMstring_Dfetch(LVdigits, LVi)), 1);
		  if (OMchar_Dillegal__char(t2))
		    {
		      signame = SLILLEGAL_CHAR;
		      goto except1;
		    }
		  OFstring_Dc2s(OMchar_Di2c(t2));
		  t3 = OMstring_Dsize(t1)
		       + OMstring_Dsize(retval_area[0])
		       + OMstring_Dsize(LVzeros);
		  t4 = OFstring_D__predict(t3);
		  OFstring_D__concat(t4, t1);
		  OFstring_D__concat(t4, retval_area[0]);
		  OFstring_D__concat(t4, LVzeros);
		  LVdigits = t4;
	        }
	      if (FALSE)
	        {
		except1:
		  if (OMstring_Dequal(signame, SLBOUNDS))
		    {
		      LVdigits = ((string) &str2);
		      if (OMint_Dgt(LVwidth, 1))
		        {
			  if (OFstring_Dsubstr(LVzeros, 1, OMint_Dsub(LVwidth, 1)) == SIG)
			    {
			      goto except0;
			    }
			  t1 = OMstring_Dsize(LVdigits)
			       + OMstring_Dsize(retval_area[0]);
			  t2 = OFstring_D__predict(t1);
			  OFstring_D__concat(t2, LVdigits);
			  OFstring_D__concat(t2, retval_area[0]);
			  LVdigits = t2;
		        }
		      LVexponent = OMint_Dadd(LVexponent, 1);
		    }
		  else
		    {
		      goto except0;
		    }
	        }
	    }
        }
    }
  t1 = LVdigits;
  t2 = LVexponent;
  retval_area[0] = t1;
  retval_area[1] = t2;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */
