/* Generated by clu2c (version 1.99.3) */
/* option, optimize time */
/* depend,f_form,_real_round*/

#include <clu2c.h>

static STRING_REP(19) str1 = {19, {'i', 'l', 'l', 'e', 'g', 'a', 'l', '_', 'f', 'i', 'e', 'l', 'd', '_', 'w', 'i', 'd', 't', 'h'}};
static STRING_REP(24) str2 = {24, {'i', 'n', 's', 'u', 'f', 'f', 'i', 'c', 'i', 'e', 'n', 't', '_', 'f', 'i', 'e', 'l', 'd', '_', 'w', 'i', 'd', 't', 'h'}};

/* begin module */
/* c_function_name, AFf__form */
/* clu_operation_name, f_form */
int AFf__form(LVx, LVint__width, LVfrac__width)
     object LVx;
     object LVint__width;
     object LVfrac__width;
{
  object LVresult= 0;
  object LVdigits= 0;
  object LVexponent= 0;
  object LVint__field__nonempty= 0;
  int t1, t2, t3, t4;
  /* begin body */
  if (OMint_Dlt(LVint__width, 0))
    {
      t2 = TRUE;
    }
  else
    {
      t2 = OMint_Dlt(LVfrac__width, 0);
    }
  if (t2)
    {
      t1 = TRUE;
    }
  else
    {
      t1 = OMint_Dlt(OMint_Dadd(LVint__width, LVfrac__width), 1);
    }
  if (t1)
    {
      signame = ((string) &str1);
      return(SIG);
    }
  OFarray_Dnew();
  LVresult = retval_area[0];
  if (OFreal_Dlt(LVx, OFreal_Dlit(0.)) == SIG)
    {
      goto except0;
    }
  if (retval_area[0])
    {
      OMarray_Daddh(LVresult, '-');
      if (OFreal_Dminus(LVx) == SIG)
        {
	  goto except0;
        }
      LVx = retval_area[0];
    }
  if (OFreal_D__unparse(LVx) == SIG)
    {
      goto except0;
    }
  LVdigits = retval_area[0];
  LVexponent = retval_area[1];
  if (AF__real__round(LVdigits, LVexponent, OMint_Dadd(OMint_Dadd(LVexponent, LVfrac__width), 1)) == SIG)
    {
      goto except1;
    }
  LVdigits = retval_area[0];
  LVexponent = retval_area[1];
  if (FALSE)
    {
    except1:
      if (OMstring_Dequal(signame, SLNEGATIVE_FIELD_WIDTH))
        {
        }
      else
        {
	  goto except0;
        }
    }
  if (OMint_Dlt(LVint__width, OMint_Dadd(LVexponent, 1)))
    {
      signame = ((string) &str2);
      return(SIG);
    }
  if (OMint_Dge(LVexponent, 0))
    {
      t1 = TRUE;
    }
  else
    {
      t1 = OMint_Dgt(LVint__width, 0);
    }
  LVint__field__nonempty = t1;
    {
      object LVi= 0;
      t1 = OMint_Dmax(LVexponent, 0);
      for (t2 = t1, t3 = OMint_Dminus(LVfrac__width); t2 >= t3; t2 -= 1)
        {
	  LVi = t2;
	    {
	      t4 = OMint_Dadd(OMint_Dsub(LVexponent, LVi), 1);
	      if (OMstring_Dbounds(LVdigits, t4))
	        {
		  signame = SLBOUNDS;
		  goto except2;
	        }
	      OMarray_Daddh(LVresult, OMstring_Dfetch(LVdigits, t4));
	      if (FALSE)
	        {
		except2:
		  if (OMstring_Dequal(signame, SLBOUNDS))
		    {
		      if (OMbool_Dnot(OMint_Dequal(LVi, 0)))
		        {
			  t4 = TRUE;
		        }
		      else
		        {
			  t4 = LVint__field__nonempty;
		        }
		      if (t4)
		        {
			  OMarray_Daddh(LVresult, '0');
		        }
		    }
		  else
		    {
		      goto except0;
		    }
	        }
	      if (OMint_Dequal(LVi, 0))
	        {
		  OMarray_Daddh(LVresult, '.');
	        }
	    }
        }
    }
  OFstring_Dac2s(LVresult);
  retval_area[0] = retval_area[0];
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */
