/* Generated by clu2c (version 1.99.3) */
/* option, optimize time */
/* depend,file_name,_check_directory_entry,_directory_with_drive,_is_atomic_directory,_is_path_delimiter,_path_delimiter,istream,pstream,split_directory_entry*/

#include <clu2c.h>

static STRING_REP(1) str1 = {1, {'.'}};
static STRING_REP(6) str2 = {6, {'o', 'u', 't', 'p', 'u', 't'}};
static STRING_REP(20) str3 = {20, {'b', 'a', 'd', ' ', 'f', 'o', 'r', 'm', 'a', 't', ' ', 'f', 'i', 'l', 'e', ' ', 'n', 'a', 'm', 'e'}};

/* begin module */
/* c_function_name, OFfile__name_Dcreate */
/* clu_operation_name, file_name$create */
int OFfile__name_Dcreate(LVdir, LVname, LVsuffix, LVother)
     object LVdir;
     object LVname;
     object LVsuffix;
     object LVother;
{
  int t1, t2, t3, t4;
  /* begin body */
  if (OFfile__name_Dcheck__dir(LVdir) == SIG)
    {
      goto except1;
    }
  LVdir = retval_area[0];
  if (FALSE)
    {
    except1:
      if (OMstring_Dequal(signame, SLBAD_FORMAT))
        {
	  return(SIG);
        }
      else
        {
	  goto except0;
        }
    }
    {
      object LVc= 0;
      for (t1 = LVname, t2 = 1, t3 = OMstring_Dsize(t1);
           t2 <= t3;
           t2++)
        {
	  LVc = OMstring_Dfetch(t1, t2);
	    {
	      if (AF__is__path__delimiter(LVc) == SIG)
	        {
		  goto except0;
	        }
	      if (retval_area[0])
	        {
		  signame = SLBAD_FORMAT;
		  return(SIG);
	        }
	    }
        }
    }
  t1 = FALSE;
  if (OMbool_Dnot(OMstring_Dempty(LVsuffix)))
    {
      if (OMstring_Dempty(LVname))
        {
	  t1 = TRUE;
        }
    }
  if (t1)
    {
      signame = SLBAD_FORMAT;
      return(SIG);
    }
    {
      object LVc= 0;
      for (t1 = LVsuffix, t2 = 1, t3 = OMstring_Dsize(t1);
           t2 <= t3;
           t2++)
        {
	  LVc = OMstring_Dfetch(t1, t2);
	    {
	      if (AF__is__path__delimiter(LVc) == SIG)
	        {
		  goto except0;
	        }
	      if (retval_area[0])
	        {
		  t4 = TRUE;
	        }
	      else
	        {
		  t4 = OMchar_Dequal(LVc, '.');
	        }
	      if (t4)
	        {
		  signame = SLBAD_FORMAT;
		  return(SIG);
	        }
	    }
        }
    }
  if (AF__check__directory__entry(LVname, LVsuffix) == SIG)
    {
      goto except2;
    }
  LVname = retval_area[0];
  LVsuffix = retval_area[1];
  if (FALSE)
    {
    except2:
      if (OMstring_Dequal(signame, SLBAD_FORMAT))
        {
	  return(SIG);
        }
      else
        {
	  goto except0;
        }
    }
  if (OMbool_Dnot(OMstring_Dempty(LVother)))
    {
      signame = SLBAD_FORMAT;
      return(SIG);
    }
  t1 = OFstruct_D__alloc(3);
  OMstruct_D__set(1, t1, LVdir);
  OMstruct_D__set(2, t1, LVname);
  OMstruct_D__set(3, t1, LVsuffix);
  retval_area[0] = t1;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFfile__name_Dget__dir */
/* clu_operation_name, file_name$get_dir */
int OFfile__name_Dget__dir(LVfn)
     object LVfn;
{
  /* begin body */
  retval_area[0] = OMstruct_Dget(1, LVfn);
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFfile__name_Dget__name */
/* clu_operation_name, file_name$get_name */
int OFfile__name_Dget__name(LVfn)
     object LVfn;
{
  /* begin body */
  retval_area[0] = OMstruct_Dget(2, LVfn);
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFfile__name_Dget__suffix */
/* clu_operation_name, file_name$get_suffix */
int OFfile__name_Dget__suffix(LVfn)
     object LVfn;
{
  /* begin body */
  retval_area[0] = OMstruct_Dget(3, LVfn);
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFfile__name_Dget__other */
/* clu_operation_name, file_name$get_other */
int OFfile__name_Dget__other(LVfn)
     object LVfn;
{
  /* begin body */
  retval_area[0] = SLNULL;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFfile__name_Dparse */
/* clu_operation_name, file_name$parse */
int OFfile__name_Dparse(LVs)
     object LVs;
{
  object LVdir= 0;
  object LVname= 0;
  object LVsuffix= 0;
  object LVfn= 0;
  /* begin body */
  if (OFfile__name_Dclip__dir(LVs) == SIG)
    {
      goto except0;
    }
  LVdir = retval_area[0];
  LVs = retval_area[1];
  if (AFsplit__directory__entry(LVs) == SIG)
    {
      goto except0;
    }
  LVname = retval_area[0];
  LVsuffix = retval_area[1];
  if (OFfile__name_Dcreate(LVdir, LVname, LVsuffix, SLNULL) == SIG)
    {
      goto except1;
    }
  LVfn = retval_area[0];
  if (FALSE)
    {
    except1:
      if (OMstring_Dequal(signame, SLBAD_FORMAT))
        {
	  return(SIG);
        }
      else
        {
	  goto except0;
        }
    }
  retval_area[0] = LVfn;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFfile__name_Dunparse */
/* clu_operation_name, file_name$unparse */
int OFfile__name_Dunparse(LVfn)
     object LVfn;
{
  object LVres= 0;
  object LVname= 0;
  int t1, t2;
  /* begin body */
  LVres = OMstruct_Dget(1, LVfn);
  if (AF__is__atomic__directory(LVres) == SIG)
    {
      goto except0;
    }
  if (OMbool_Dnot(retval_area[0]))
    {
      if (AF__path__delimiter() == SIG)
        {
	  goto except0;
        }
      OFstring_Dappend(LVres, retval_area[0]);
      LVres = retval_area[0];
    }
  LVname = OMstruct_Dget(2, LVfn);
  if (OMbool_Dnot(OMstring_Dempty(LVname)))
    {
      object LVsuffix= 0;
      t1 = OMstring_Dsize(LVres)
           + OMstring_Dsize(LVname);
      t2 = OFstring_D__predict(t1);
      OFstring_D__concat(t2, LVres);
      OFstring_D__concat(t2, LVname);
      LVres = t2;
      LVsuffix = OMstruct_Dget(3, LVfn);
      if (OMbool_Dnot(OMstring_Dempty(LVsuffix)))
        {
	  t1 = OMstring_Dsize(LVres)
	       + OMstring_Dsize(((string) &str1))
	       + OMstring_Dsize(LVsuffix);
	  t2 = OFstring_D__predict(t1);
	  OFstring_D__concat(t2, LVres);
	  OFstring_D__concat(t2, ((string) &str1));
	  OFstring_D__concat(t2, LVsuffix);
	  LVres = t2;
        }
    }
  retval_area[0] = LVres;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFfile__name_Dmake__output */
/* clu_operation_name, file_name$make_output */
int OFfile__name_Dmake__output(LVfn, LVsuffix)
     object LVfn;
     object LVsuffix;
{
  object LVname= 0;
  /* begin body */
  LVname = OMstruct_Dget(2, LVfn);
  if (OMstring_Dempty(LVname))
    {
      LVname = ((string) &str2);
    }
  if (OFfile__name_Dcreate(OMstruct_Dget(1, LVfn), LVname, LVsuffix, SLNULL) == SIG)
    {
      goto except1;
    }
  retval_area[0] = retval_area[0];
  return RET;
  if (FALSE)
    {
    except1:
      if (OMstring_Dequal(signame, SLBAD_FORMAT))
        {
	  return(SIG);
        }
      else
        {
	  goto except0;
        }
    }
  /* end body */
  noretval(SLNULL);
  return(SIG);
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFfile__name_Dmake__temp */
/* clu_operation_name, file_name$make_temp */
int OFfile__name_Dmake__temp(LVdir, LVprog, LVfile__id)
     object LVdir;
     object LVprog;
     object LVfile__id;
{
  /* begin body */
  if (OFfile__name_Dcreate(LVdir, LVprog, LVfile__id, SLNULL) == SIG)
    {
      goto except1;
    }
  retval_area[0] = retval_area[0];
  return RET;
  if (FALSE)
    {
    except1:
      if (OMstring_Dequal(signame, SLBAD_FORMAT))
        {
	  return(SIG);
        }
      else
        {
	  goto except0;
        }
    }
  /* end body */
  noretval(SLNULL);
  return(SIG);
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFfile__name_Dequal */
/* clu_operation_name, file_name$equal */
int OFfile__name_Dequal(LVfn1, LVfn2)
     object LVfn1;
     object LVfn2;
{
  int t1, t2, t3, t4, t5;
  /* begin body */
  t1 = FALSE;
  t2 = FALSE;
  t3 = OMstruct_Dget(1, LVfn1);
  if (OMstring_Dequal(t3, OMstruct_Dget(1, LVfn2)))
    {
      t4 = OMstruct_Dget(2, LVfn1);
      if (OMstring_Dequal(t4, OMstruct_Dget(2, LVfn2)))
        {
	  t2 = TRUE;
        }
    }
  if (t2)
    {
      t5 = OMstruct_Dget(3, LVfn1);
      if (OMstring_Dequal(t5, OMstruct_Dget(3, LVfn2)))
        {
	  t1 = TRUE;
        }
    }
  retval_area[0] = t1;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFfile__name_Dsimilar */
/* clu_operation_name, file_name$similar */
int OFfile__name_Dsimilar(LVfn1, LVfn2)
     object LVfn1;
     object LVfn2;
{
  /* begin body */
  if (OFfile__name_Dequal(LVfn1, LVfn2) == SIG)
    {
      goto except0;
    }
  retval_area[0] = retval_area[0];
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFfile__name_Dcopy */
/* clu_operation_name, file_name$copy */
int OFfile__name_Dcopy(LVfn)
     object LVfn;
{
  /* begin body */
  retval_area[0] = LVfn;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFfile__name_Dencode */
/* clu_operation_name, file_name$encode */
int OFfile__name_Dencode(LVfn, LVist)
     object LVfn;
     object LVist;
{
  /* begin body */
  if (OFfile__name_Dunparse(LVfn) == SIG)
    {
      goto except1;
    }
  if (OFstring_Dencode(retval_area[0], LVist) == SIG)
    {
      goto except1;
    }
  if (FALSE)
    {
    except1:
      if (OMstring_Dequal(signame, SLNOT_POSSIBLE))
        {
	  return(SIG);
        }
      else
        {
	  goto except0;
        }
    }
  /* end body */
  return(RET);
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFfile__name_Ddecode */
/* clu_operation_name, file_name$decode */
int OFfile__name_Ddecode(LVist)
     object LVist;
{
  object LVs= 0;
  object LVfn= 0;
  /* begin body */
  if (OFstring_Ddecode(LVist) == SIG)
    {
      goto except1;
    }
  LVs = retval_area[0];
  if (FALSE)
    {
    except1:
      if (OMstring_Dequal(signame, SLNOT_POSSIBLE))
        {
	  return(SIG);
        }
      else
        {
	  goto except0;
        }
    }
  if (OFfile__name_Dparse(LVs) == SIG)
    {
      goto except2;
    }
  LVfn = retval_area[0];
  if (FALSE)
    {
    except2:
      if (OMstring_Dequal(signame, SLBAD_FORMAT))
        {
	  sigarg_area[0] = ((string) &str3);
	  signame = SLNOT_POSSIBLE;
	  return(SIG);
        }
      else
        {
	  goto except0;
        }
    }
  retval_area[0] = LVfn;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFfile__name_Dprint */
/* clu_operation_name, file_name$print */
int OFfile__name_Dprint(LVfn, LVpst)
     object LVfn;
     object LVpst;
{
  /* begin body */
  if (OFfile__name_Dunparse(LVfn) == SIG)
    {
      goto except0;
    }
  if (OFpstream_Dtext(LVpst, retval_area[0]) == SIG)
    {
      goto except0;
    }
  /* end body */
  return(RET);
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFfile__name_Dcheck__dir */
/* clu_operation_name, file_name$check_dir */
int OFfile__name_Dcheck__dir(LVdir)
     object LVdir;
{
  object LVdrive= 0;
  object LVpath= 0;
  int t1, t2, t3, t4;
  /* begin body */
  if (OFfile__name_Dclip__drive(LVdir) == SIG)
    {
      goto except0;
    }
  LVdrive = retval_area[0];
  LVdir = retval_area[1];
  if (OFfile__name_Dchop__trailing__delims(LVdir) == SIG)
    {
      goto except0;
    }
  LVdir = retval_area[0];
  OFarray_Dnew();
  LVpath = retval_area[0];
    {
      object LVent= 0;
      for (t1 = OFfile__name_Dtrace__entries(TRUE, &t2, LVdir);
           t1 == YIELD;
           t1 = OFfile__name_Dtrace__entries(FALSE, &t2, 0))
        {
	  LVent = retval_area[0];
	    {
	      object LVname= 0;
	      object LVsuffix= 0;
	      if (OMstring_Dempty(LVent))
	        {
		  continue;
	        }
	      if (AFsplit__directory__entry(LVent) == SIG)
	        {
		  goto except0;
	        }
	      LVname = retval_area[0];
	      LVsuffix = retval_area[1];
	      if (AF__check__directory__entry(LVname, LVsuffix) == SIG)
	        {
		  goto except1;
	        }
	      LVname = retval_area[0];
	      LVsuffix = retval_area[1];
	      if (FALSE)
	        {
		except1:
		  if (OMstring_Dequal(signame, SLBAD_FORMAT))
		    {
		      return(SIG);
		    }
		  else
		    {
		      goto except0;
		    }
	        }
	      if (OMstring_Dempty(LVsuffix))
	        {
		  LVent = LVname;
	        }
	      else
	        {
		  t3 = OMstring_Dsize(LVname)
		       + OMstring_Dsize(((string) &str1))
		       + OMstring_Dsize(LVsuffix);
		  t4 = OFstring_D__predict(t3);
		  OFstring_D__concat(t4, LVname);
		  OFstring_D__concat(t4, ((string) &str1));
		  OFstring_D__concat(t4, LVsuffix);
		  LVent = t4;
	        }
	      OMarray_Daddh(LVpath, LVent);
	    }
        }
      free(t2);
      if (t1 == SIG)
        {
	  goto except0;
        }
    }
  if (OFfile__name_Dconcat__entries(LVpath) == SIG)
    {
      goto except0;
    }
  LVdir = retval_area[0];
  if (OMbool_Dnot(OMstring_Dempty(LVdrive)))
    {
      t1 = OMstring_Dsize(LVdrive)
           + OMstring_Dsize(LVdir);
      t2 = OFstring_D__predict(t1);
      OFstring_D__concat(t2, LVdrive);
      OFstring_D__concat(t2, LVdir);
      LVdir = t2;
    }
  retval_area[0] = LVdir;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFfile__name_Dclip__dir */
/* clu_operation_name, file_name$clip_dir */
int OFfile__name_Dclip__dir(LVs)
     object LVs;
{
  object LVdrive= 0;
  object LVi= 0;
  object LVdir= 0;
  object LVrest= 0;
  int t1, t2;
  /* begin body */
  if (OFfile__name_Dclip__drive(LVs) == SIG)
    {
      goto except0;
    }
  LVdrive = retval_area[0];
  LVs = retval_area[1];
  LVi = OMstring_Dsize(LVs);
  while (TRUE)
    {
      if (OMstring_Dbounds(LVs, LVi))
        {
	  signame = SLBOUNDS;
	  goto except1;
        }
      if (AF__is__path__delimiter(OMstring_Dfetch(LVs, LVi)) == SIG)
        {
	  goto except1;
        }
      if (!OMbool_Dnot(retval_area[0]))
        {
	  break;
        }
        {
	  LVi = OMint_Dsub(LVi, 1);
        }
    }
  if (FALSE)
    {
    except1:
      if (OMstring_Dequal(signame, SLBOUNDS))
        {
        }
      else
        {
	  goto except0;
        }
    }
  if (OMint_Dequal(LVi, 0))
    {
      LVdir = SLNULL;
      LVrest = LVs;
    }
  else
    {
      if (OMint_Dequal(LVi, 1))
        {
	  if (AF__path__delimiter() == SIG)
	    {
	      goto except0;
	    }
	  OFstring_Dc2s(retval_area[0]);
	  LVdir = retval_area[0];
	  if (OFstring_Drest(LVs, 2) == SIG)
	    {
	      goto except0;
	    }
	  LVrest = retval_area[0];
        }
      else
        {
	  if (OFstring_Dsubstr(LVs, 1, OMint_Dsub(LVi, 1)) == SIG)
	    {
	      goto except0;
	    }
	  LVdir = retval_area[0];
	  if (OFstring_Drest(LVs, OMint_Dadd(LVi, 1)) == SIG)
	    {
	      goto except0;
	    }
	  LVrest = retval_area[0];
        }
    }
  if (OMbool_Dnot(OMstring_Dempty(LVdrive)))
    {
      t1 = OMstring_Dsize(LVdrive)
           + OMstring_Dsize(LVdir);
      t2 = OFstring_D__predict(t1);
      OFstring_D__concat(t2, LVdrive);
      OFstring_D__concat(t2, LVdir);
      LVdir = t2;
    }
  t1 = LVdir;
  t2 = LVrest;
  retval_area[0] = t1;
  retval_area[1] = t2;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFfile__name_Dclip__drive */
/* clu_operation_name, file_name$clip_drive */
int OFfile__name_Dclip__drive(LVdir)
     object LVdir;
{
  object LVdrive= 0;
  object LVc= 0;
  int t1, t2;
  /* begin body */
  if (AF__directory__with__drive(LVdir) == SIG)
    {
      goto except0;
    }
  if (OMbool_Dnot(retval_area[0]))
    {
      t1 = SLNULL;
      t2 = LVdir;
      retval_area[0] = t1;
      retval_area[1] = t2;
      return RET;
    }
  if (OMstring_Dbounds(LVdir, 1))
    {
      signame = SLBOUNDS;
      goto except0;
    }
  LVc = OMstring_Dfetch(LVdir, 1);
  t1 = OMchar_Dle('A', LVc);
  if (OMbool_Dand(t1, OMchar_Dle(LVc, 'Z')))
    {
      t2 = OMint_Dadd(OMchar_Dc2i(LVc), 32);
      if (OMchar_Dillegal__char(t2))
        {
	  signame = SLILLEGAL_CHAR;
	  goto except0;
        }
      OFstring_Dc2s(OMchar_Di2c(t2));
      OFstring_Dappend(retval_area[0], ':');
      LVdrive = retval_area[0];
    }
  else
    {
      if (OFstring_Dsubstr(LVdir, 1, 2) == SIG)
        {
	  goto except0;
        }
      LVdrive = retval_area[0];
    }
  if (OFstring_Drest(LVdir, 3) == SIG)
    {
      goto except0;
    }
  t1 = LVdrive;
  t2 = retval_area[0];
  retval_area[0] = t1;
  retval_area[1] = t2;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFfile__name_Dconcat__entries */
/* clu_operation_name, file_name$concat_entries */
int OFfile__name_Dconcat__entries(LVpath)
     object LVpath;
{
  object LVdir= 0;
  object LVfirst= 0;
  int t1, t2, t3, t4, t5;
  /* begin body */
  if (OMarray_Dempty(LVpath))
    {
      retval_area[0] = SLNULL;
      return RET;
    }
  else
    {
      if (OMint_Dequal(OMarray_Dsize(LVpath), 1))
        {
	  if (OMarray_Dempty(LVpath))
	    {
	      signame = SLBOUNDS;
	      goto except0;
	    }
	  retval_area[0] = OMarray_Dbottom(LVpath);
	  return RET;
        }
    }
  if (OMarray_Dempty(LVpath))
    {
      signame = SLBOUNDS;
      goto except0;
    }
  LVfirst = OMarray_Dreml(LVpath);
  t1 = FALSE;
  if (OMint_Dequal(OMstring_Dsize(LVfirst), 1))
    {
      if (OMstring_Dbounds(LVfirst, 1))
        {
	  signame = SLBOUNDS;
	  goto except0;
        }
      if (AF__is__path__delimiter(OMstring_Dfetch(LVfirst, 1)) == SIG)
        {
	  goto except0;
        }
      if (retval_area[0])
        {
	  t1 = TRUE;
        }
    }
  if (t1)
    {
      LVdir = SLNULL;
    }
  else
    {
      LVdir = LVfirst;
    }
    {
      object LVent= 0;
      for (t1 = LVpath, t2 = OMarray_Dlow(t1), t3 = OMarray_Dhigh(t1);
           t2 <= t3;
           t2++)
        {
	  LVent = OMarray_Dfetch(t1, t2);
	    {
	      if (AF__path__delimiter() == SIG)
	        {
		  goto except0;
	        }
	      OFstring_Dappend(LVdir, retval_area[0]);
	      t4 = OMstring_Dsize(retval_area[0])
	           + OMstring_Dsize(LVent);
	      t5 = OFstring_D__predict(t4);
	      OFstring_D__concat(t5, retval_area[0]);
	      OFstring_D__concat(t5, LVent);
	      LVdir = t5;
	    }
        }
    }
  retval_area[0] = LVdir;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFfile__name_Dchop__trailing__delims */
/* clu_operation_name, file_name$chop_trailing_delims */
int OFfile__name_Dchop__trailing__delims(LVs)
     object LVs;
{
  object LVsize= 0;
  object LVi= 0;
  int t1;
  /* begin body */
  LVsize = OMstring_Dsize(LVs);
  LVi = LVsize;
  while (TRUE)
    {
      t1 = FALSE;
      if (OMint_Dgt(LVi, 1))
        {
	  if (OMstring_Dbounds(LVs, LVi))
	    {
	      signame = SLBOUNDS;
	      goto except0;
	    }
	  if (AF__is__path__delimiter(OMstring_Dfetch(LVs, LVi)) == SIG)
	    {
	      goto except0;
	    }
	  if (retval_area[0])
	    {
	      t1 = TRUE;
	    }
        }
      if (!t1)
        {
	  break;
        }
        {
	  LVi = OMint_Dsub(LVi, 1);
        }
    }
  if (OMint_Dlt(LVi, LVsize))
    {
      if (OFstring_Dsubstr(LVs, 1, LVi) == SIG)
        {
	  goto except0;
        }
      LVs = retval_area[0];
    }
  retval_area[0] = LVs;
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* c_function_name, OFfile__name_Dtrace__entries */
/* clu_operation_name, file_name$trace_entries */
#define INV_TOP 5
#define WORK_SIZE 7
int OFfile__name_Dtrace__entries(init, ivarp, LVdir)
     bool init;
     int **ivarp;
     object LVdir;
{
  if (init)
    {
      *ivarp = (int*) malloc(WORK_SIZE*sizeof(int));
      (*ivarp)[1] = LVdir;
    }
  else
    {
      switch ((*ivarp)[0])
  	{
  	  case 1: goto yield1;
  	  case 2: goto yield2;
  	  case 3: goto yield3;
  	}
    }
  /* begin body */
  (*ivarp)[2] = 1;
  if (OMstring_Dbounds((*ivarp)[1], 1))
    {
      signame = SLBOUNDS;
      goto except1;
    }
  if (AF__is__path__delimiter(OMstring_Dfetch((*ivarp)[1], 1)) == SIG)
    {
      goto except1;
    }
  if (retval_area[0])
    {
      if (AF__path__delimiter() == SIG)
        {
	  goto except1;
        }
      OFstring_Dc2s(retval_area[0]);
      retval_area[0] = retval_area[0];
      (*ivarp)[0] = 1;
      return YIELD;
    yield1:
      NO_OPERATION;
      (*ivarp)[2] = 2;
    }
  if (FALSE)
    {
    except1:
      if (OMstring_Dequal(signame, SLBOUNDS))
        {
	  return RET;
        }
      else
        {
	  goto except0;
        }
    }
  (*ivarp)[3] = OMstring_Dsize((*ivarp)[1]);
    {
      for ((*ivarp)[INV_TOP+0] = (*ivarp)[2], (*ivarp)[INV_TOP+1] = (*ivarp)[3]; (*ivarp)[INV_TOP+0] <= (*ivarp)[INV_TOP+1]; (*ivarp)[INV_TOP+0]++)
        {
	  (*ivarp)[4] = (*ivarp)[INV_TOP+0];
	    {
	      if (OMstring_Dbounds((*ivarp)[1], (*ivarp)[4]))
	        {
		  signame = SLBOUNDS;
		  goto except0;
	        }
	      if (AF__is__path__delimiter(OMstring_Dfetch((*ivarp)[1], (*ivarp)[4])) == SIG)
	        {
		  goto except0;
	        }
	      if (retval_area[0])
	        {
		  if (OFstring_Dsubstr((*ivarp)[1], (*ivarp)[2], OMint_Dsub((*ivarp)[4], (*ivarp)[2])) == SIG)
		    {
		      goto except0;
		    }
		  retval_area[0] = retval_area[0];
		  (*ivarp)[0] = 2;
		  return YIELD;
		yield2:
		  NO_OPERATION;
		  (*ivarp)[2] = OMint_Dadd((*ivarp)[4], 1);
	        }
	    }
        }
    }
  if (OMint_Dle((*ivarp)[2], (*ivarp)[3]))
    {
      if (OFstring_Drest((*ivarp)[1], (*ivarp)[2]) == SIG)
        {
	  goto except0;
        }
      retval_area[0] = retval_area[0];
      (*ivarp)[0] = 3;
      return YIELD;
    yield3:
      NO_OPERATION;
    }
  /* end body */
  return(RET);
except0:
  out_handler(SLNULL);
  return(SIG);
}
#undef INV_TOP
#undef WORK_SIZE
/* end module */
