/* Generated by clu2c (version 1.99.3) */
/* option, optimize time */
/* depend,g_form,e_form,f_form*/

#include <clu2c.h>

static STRING_REP(19) str1 = {19, {'i', 'l', 'l', 'e', 'g', 'a', 'l', '_', 'f', 'i', 'e', 'l', 'd', '_', 'w', 'i', 'd', 't', 'h'}};
static STRING_REP(24) str2 = {24, {'i', 'n', 's', 'u', 'f', 'f', 'i', 'c', 'i', 'e', 'n', 't', '_', 'f', 'i', 'e', 'l', 'd', '_', 'w', 'i', 'd', 't', 'h'}};

/* begin module */
/* c_function_name, AFg__form */
/* clu_operation_name, g_form */
int AFg__form(LVx, LVint__width, LVfrac__width)
     object LVx;
     object LVint__width;
     object LVfrac__width;
{
  static bool IV = FALSE;
  static object WVexp__width= 0;
  int t1;
  if (IV == FALSE)
    {
      IV = TRUE;
      if (OFreal_D__exp__width() == SIG)
        {
	  goto except0;
        }
      WVexp__width = retval_area[0];
    }
  /* begin body */
  if (OFreal_Dequal(LVx, OFreal_Dlit(0.)) == SIG)
    {
      goto except1;
    }
  if (retval_area[0])
    {
      if (AFf__form(LVx, LVint__width, LVfrac__width) == SIG)
        {
	  goto except1;
        }
      retval_area[0] = retval_area[0];
      return RET;
    }
  else
    {
      object LVexponent= 0;
      if (OFreal_Dexponent(LVx) == SIG)
        {
	  goto except1;
        }
      LVexponent = retval_area[0];
      t1 = FALSE;
      if (OMint_Dle(-1, LVexponent))
        {
	  if (OMint_Dlt(LVexponent, LVint__width))
	    {
	      t1 = TRUE;
	    }
        }
      if (t1)
        {
	  if (AFf__form(LVx, LVint__width, LVfrac__width) == SIG)
	    {
	      goto except1;
	    }
	  retval_area[0] = retval_area[0];
	  return RET;
        }
      else
        {
	  if (AFe__form(LVx, 1, OMint_Dsub(OMint_Dsub(OMint_Dadd(LVint__width, LVfrac__width), WVexp__width), 3)) == SIG)
	    {
	      goto except1;
	    }
	  retval_area[0] = retval_area[0];
	  return RET;
        }
    }
  if (FALSE)
    {
    except1:
      if (OMstring_Dequal(signame, ((string) &str1)) || OMstring_Dequal(signame, ((string) &str2)))
        {
	  return(SIG);
        }
      else
        {
	  goto except0;
        }
    }
  /* end body */
  noretval(SLNULL);
  return(SIG);
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */
