/* Generated by clu2c (version 1.99.3) */
/* option, optimize time */
/* depend,now,_external_gettime,date*/

#include <clu2c.h>

/* begin module */
/* c_function_name, AFnow */
/* clu_operation_name, now */
int AFnow()
{
  object LVyear= 0;
  object LVmonth= 0;
  object LVday= 0;
  object LVhour= 0;
  object LVmin= 0;
  object LVsec= 0;
  /* begin body */
  if (AF__external__gettime() == SIG)
    {
      goto except0;
    }
  LVyear = retval_area[0];
  LVmonth = retval_area[1];
  LVday = retval_area[2];
  LVhour = retval_area[3];
  LVmin = retval_area[4];
  LVsec = retval_area[5];
  if (OFdate_Dcreate(LVday, LVmonth, LVyear, LVhour, LVmin, LVsec) == SIG)
    {
      goto except0;
    }
  retval_area[0] = retval_area[0];
  return RET;
  /* end body */
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */
