/* Generated by clu2c (version 1.99.3) */
/* option, optimize time */
/* depend,rename_file,_external_rename,file_name,file_name_to_string*/

#include <clu2c.h>

/* begin module */
/* c_function_name, AFrename__file */
/* clu_operation_name, rename_file */
int AFrename__file(LVold, LVnew)
     object LVold;
     object LVnew;
{
  int t1;
  /* begin body */
  if (AFfile__name__to__string(LVold) == SIG)
    {
      goto except1;
    }
  t1 = retval_area[0];
  if (AFfile__name__to__string(LVnew) == SIG)
    {
      goto except1;
    }
  if (AF__external__rename(t1, retval_area[0]) == SIG)
    {
      goto except1;
    }
  if (FALSE)
    {
    except1:
      if (OMstring_Dequal(signame, SLNOT_POSSIBLE))
        {
	  return(SIG);
        }
      else
        {
	  goto except0;
        }
    }
  /* end body */
  return(RET);
except0:
  out_handler(SLNULL);
  return(SIG);
}
/* end module */
