#!/usr/local/bin/perl

# dosfile - convert a file to MS-DOS format
#
# Copyright (c) 1996
#	Department of Mathematical and Computing Sciences,
#	Tokyo Institute of Technology.  All rights reserved.
#
# $Id: dosfile,v 2.0 1996/06/10 09:06:12 ushijima Exp $


# Program for converting into Shift-JIS.
$to_sjis = '/usr/local/bin/nkf -s';

# Command line analysis.
if ($#ARGV == 1) {
    $infile = $ARGV[0];
    $outfile = $ARGV[1];
} else {
    die("usage: dosfile infile outfile\n");
}

# Checks if input file can be opened.
open(INPUT, "$infile") || die("$infile: $!\n");
close(INPUT);

open(INPUT, "$to_sjis $infile |");
open(OUTPUT, ">$outfile") || die("$outfile: $!\n");
while (<INPUT>) {
    s/$/\015/;
    print(OUTPUT);
}
close(INPUT);
close(OUTPUT);

utime((stat($infile))[8, 9], $outfile) || die("$outfile: $!\n");

exit(0);
