

######################################################################
#
# Makefile.unix.  Generated automatically from Makefile.in by m4.
#


#### Variables specific to this directory ####

# Current directory relative to the top-level build directory
curdir = lib/stdio

# Top-level build directory
topdir = ../..

# Default flags to plink
DEFAULT_PLINKFLAGS = -x

# All the flags to plink
ALL_PLINKFLAGS = $(DEFAULT_PLINKFLAGS) $(PLINKFLAGS)

# Command line to fake clu2c execution
FAKE_CLU2C = sh $(top_srcdir)/fakeclu.sh

# Command line to execute plink
REAL_PLINK = $(PLINK) $(ALL_PLINKFLAGS) -o $(POUT).c $(CLU_INT)

# Command line to fake plink execution
FAKE_PLINK = $(LN_S) $(srcdir)/pretrans/$(POUT).c $(POUT).c

# Default flags to the C compiler
DEFAULT_CFLAGS = -I$(top_srcdir)/include -w -I$(topdir)

# All the flags to the C compiler
ALL_CFLAGS = $(DEFAULT_CFLAGS) $(CFLAGS)

# Archive file
ARCHIVE = ../libclu2c.a


#### Source files ####

# C source files
C_SRC = $(C_SRC_1)
C_SRC_1 = istream.c stream.c

# CLU source files
CLU_SRC = $(CLU_SRC_1) $(CLU_SRC_2) $(CLU_SRC_3)
CLU_SRC_1 = date.clu del_file.clu e_form.clu f_form.clu fname.clu
CLU_SRC_2 = g_form.clu now.clu ren_file.clu set_wdir.clu username.clu
CLU_SRC_3 = wdir.clu

# Miscellaneous source files
MISC_SRC = ChangeLog Makefile.in README LIB.xld

# All the source files
ALL_SRC = $(C_SRC) $(CLU_SRC) $(MISC_SRC)


#### Created files ####

# Object files compiled from C source files
C_OBJ = $(C_OBJ_1)
C_OBJ_1 = istream.o stream.o

# Intermediate C files translated from CLU files
CLU_INT = $(CLU_INT_1) $(CLU_INT_2) $(CLU_INT_3)
CLU_INT_1 = date.c del_file.c e_form.c f_form.c fname.c
CLU_INT_2 = g_form.c now.c ren_file.c set_wdir.c username.c
CLU_INT_3 = wdir.c

# Object files compiled from intermediate C files
CLU_OBJ = $(CLU_OBJ_1) $(CLU_OBJ_2) $(CLU_OBJ_3)
CLU_OBJ_1 = date.o del_file.o e_form.o f_form.o fname.o
CLU_OBJ_2 = g_form.o now.o ren_file.o set_wdir.o username.o
CLU_OBJ_3 = wdir.o

# Base name of output file of plink
POUT = op-table

# Pre-translated C files
PRE = $(CLU_INT) $(POUT).c

# All the object files
ALL_OBJ = $(CLU_OBJ) $(C_OBJ)


#### Variables for source code maintenance ####

# Non-source files included in the distribution
NON_SRC = Makefile.dos Makefile.unix fakeclu.bat

# All the files included in the distribution
DIST = $(ALL_SRC) $(NON_SRC)

# Default flags to m4
DEFAULT_M4FLAGS = -I$(top_srcdir)/mk

# All the flags to m4
ALL_M4FLAGS = $(DEFAULT_M4FLAGS) $(M4FLAGS)


#### Rules for standard targets ####

# Compiles the entire program
all: archive $(POUT).c

# Copies all the products
install: all

# Removes installed files
uninstall:

# Makes mostly clean
mostlyclean:
	rm -f archive
	rm -f $(C_OBJ)
	rm -f $(CLU_OBJ)

# Makes clean
clean:
	rm -f archive
	rm -f SPC.lib clu2c.time $(POUT).c
	rm -f $(C_OBJ)
	rm -f $(CLU_INT)
	rm -f $(CLU_OBJ)

# Makes clean as disributed
distclean:
	rm -f Makefile Makefile.top
	rm -f archive
	rm -f SPC.lib clu2c.time $(POUT).c
	rm -f $(C_OBJ)
	rm -f $(CLU_INT)
	rm -f $(CLU_OBJ)

# Makes really clean
realclean:
	rm -f Makefile Makefile.top
	rm -f archive
	rm -f SPC.lib clu2c.time $(POUT).c
	rm -f $(C_OBJ)
	rm -f $(CLU_INT)
	rm -f $(CLU_OBJ)

# Creates tag file
TAGS:

# Creates info file
info:

# Creates distribution
dist: $(DIST) $(PRE)
	@$(top_srcdir)/config/makedist $(distname) $(curdir) $(DIST)
	@$(top_srcdir)/config/makedist -p $(distname) $(curdir) $(PRE)

# Does some check
check:


#### Rules specific to this directory ####

# Creates stream.o
stream.o: $(srcdir)/stream.c
	$(CC) $(ALL_CFLAGS) -c $(srcdir)/stream.c

# Creates all the C files
cfiles: clu2c.time $(POUT).c

# Translates all the CLU source files to C files
clu2c.time: $(CLU_SRC)
	$(CLU2C) $(CLU2CFLAGS) --make
	echo clu2c.time > clu2c.time

# Pre-link
$(POUT).c: $(CLU_INT)
	$(PLINK_METHOD)

# Archives object files in this directory
archive: $(ALL_OBJ)
	$(AR) $(ARFLAGS) $(ARCHIVE) $(CLU_OBJ)
	$(AR) $(ARFLAGS) $(ARCHIVE) $(C_OBJ)
	$(RANLIB) $(ARCHIVE)
	echo archive > archive

# Creates makefiles for this directory and all the subdirectories
mkfiles:
	cat Makefile.top $(topdir)/config.mk $(srcdir)/Makefile.unix > Makefile

# Forces a particular target to be made
always:


#### Suffix rules ####

.SUFFIXES:
.SUFFIXES: .o .c .clu

# Compiles CLU files
.clu.c:
	rm -f clu2c.time
	$(MAKE) clu2c.time

# Compiles C file to get object file
.c.o:
	$(CC) $(ALL_CFLAGS) -c $<


#### Rules for source code maintenance ####

# Creates fakeclu.bat
fakeclu.bat: Makefile
	@echo creating fakeclu.bat
	@echo echo off > fakeclu.bat
	@echo rem fakeclu.bat.\  Generated automatically by make. >> fakeclu.bat
	@for i in $(CLU_INT); do \
		echo echo preparing $$i >>fakeclu.bat; \
		echo "if not exist $$i copy pretrans\\$$i $$i >nul" >> fakeclu.bat; \
	done

# Deletes all files created by making cfiles
cfiles-clean:
	rm -f $(CLU_INT) $(POUT).c SPC.lib clu2c.time

# Processes m4 files
m4:
	@for os in unix dos; do					\
	    mk=Makefile.$$os;						\
	    echo creating $$mk;						\
	    $(M4) $(ALL_M4FLAGS) -DOSTYPE=$$os Makefile.in >$$mk.new;	\
	    if test ! $$?; then						\
		echo $$mk is unchanged;					\
		rm -f $$mk.new;						\
		exit 1;							\
	    elif cmp -s $$mk $$mk.new 2>/dev/null; then			\
		echo $$mk is unchanged;					\
		rm -f $$mk.new;						\
	    else							\
		rm -f $$mk;						\
		mv $$mk.new $$mk;					\
	    fi;								\
	done

# Creates dos distribution
dosdist: $(DIST) $(PRE)
	@$(top_srcdir)/config/makedist -d $(dos_distname) $(curdir) $(DIST)
	@$(top_srcdir)/config/makedist -d -p $(dos_distname) $(curdir) $(PRE)

# Creates the list of source files
source-list:
	@if [ $(curdir) = . ]; then\
	    cp /dev/null source-list;\
	    for i in $(ALL_SRC); do\
		echo $$i >>source-list;\
	    done;\
	else\
	    for i in $(ALL_SRC); do\
		echo $(curdir)/$$i >>$(topdir)/source-list;\
	    done;\
	fi
