

######################################################################
#
# Makefile.dos.  Generated automatically from Makefile.in by m4.
#


#### Variables specific to this directory ####

# Current directory relative to the top-level build directory
curdir = lib\stdio

# Top-level build directory
topdir = ../..

# Default flags to plink
DEFAULT_PLINKFLAGS = -x

# All the flags to plink
ALL_PLINKFLAGS = $(DEFAULT_PLINKFLAGS) $(PLINKFLAGS)

# Command line to fake clu2c execution
FAKE_CLU2C = $(COMMAND) $(COMMANDFLAGS) /c fakeclu

# Command line to execute plink
REAL_PLINK = $(PLINK) $(ALL_PLINKFLAGS) -o $(POUT).c $(CLU_INT)

# Command line to fake plink execution
FAKE_PLINK = $(LN_S) $(srcdir)\pretrans\$(POUT).c $(POUT).c

# Default flags to the C compiler
DEFAULT_CFLAGS = -I$(top_srcdir)/include -w -I$(topdir)

# All the flags to the C compiler
ALL_CFLAGS = $(DEFAULT_CFLAGS) $(CFLAGS)

# Archive file
ARCHIVE = ../libclu2c.a


#### Source files ####

# C source files
C_SRC = $(C_SRC_1)
C_SRC_1 = istream.c stream.c

# CLU source files
CLU_SRC = $(CLU_SRC_1) $(CLU_SRC_2) $(CLU_SRC_3)
CLU_SRC_1 = date.clu del_file.clu e_form.clu f_form.clu fname.clu
CLU_SRC_2 = g_form.clu now.clu ren_file.clu set_wdir.clu username.clu
CLU_SRC_3 = wdir.clu

# Miscellaneous source files
MISC_SRC = ChangeLog Makefile.in README LIB.xld

# All the source files
ALL_SRC = $(C_SRC) $(CLU_SRC) $(MISC_SRC)


#### Created files ####

# Object files compiled from C source files
C_OBJ = $(C_OBJ_1)
C_OBJ_1 = istream.o stream.o

# Intermediate C files translated from CLU files
CLU_INT = $(CLU_INT_1) $(CLU_INT_2) $(CLU_INT_3)
CLU_INT_1 = date.c del_file.c e_form.c f_form.c fname.c
CLU_INT_2 = g_form.c now.c ren_file.c set_wdir.c username.c
CLU_INT_3 = wdir.c

# Object files compiled from intermediate C files
CLU_OBJ = $(CLU_OBJ_1) $(CLU_OBJ_2) $(CLU_OBJ_3)
CLU_OBJ_1 = date.o del_file.o e_form.o f_form.o fname.o
CLU_OBJ_2 = g_form.o now.o ren_file.o set_wdir.o username.o
CLU_OBJ_3 = wdir.o

# Base name of output file of plink
POUT = op-table

# Pre-translated C files
PRE = $(CLU_INT) $(POUT).c

# All the object files
ALL_OBJ = $(CLU_OBJ) $(C_OBJ)


#### Rules for standard targets ####

# Compiles the entire program
all: archive $(POUT).c

# Copies all the products
install: all

# Removes installed files
uninstall:

# Makes mostly clean
mostlyclean:
	$(COMMAND) $(COMMANDFLAGS) /c ..\..\config\remove archive
	$(COMMAND) $(COMMANDFLAGS) /c ..\..\config\remove $(C_OBJ_1)
	$(COMMAND) $(COMMANDFLAGS) /c ..\..\config\remove $(CLU_OBJ_1)
	$(COMMAND) $(COMMANDFLAGS) /c ..\..\config\remove $(CLU_OBJ_2)
	$(COMMAND) $(COMMANDFLAGS) /c ..\..\config\remove $(CLU_OBJ_3)

# Makes clean
clean:
	$(COMMAND) $(COMMANDFLAGS) /c ..\..\config\remove archive
	$(COMMAND) $(COMMANDFLAGS) /c ..\..\config\remove SPC.lib clu2c.time $(POUT).c
	$(COMMAND) $(COMMANDFLAGS) /c ..\..\config\remove $(C_OBJ_1)
	$(COMMAND) $(COMMANDFLAGS) /c ..\..\config\remove $(CLU_INT_1)
	$(COMMAND) $(COMMANDFLAGS) /c ..\..\config\remove $(CLU_INT_2)
	$(COMMAND) $(COMMANDFLAGS) /c ..\..\config\remove $(CLU_INT_3)
	$(COMMAND) $(COMMANDFLAGS) /c ..\..\config\remove $(CLU_OBJ_1)
	$(COMMAND) $(COMMANDFLAGS) /c ..\..\config\remove $(CLU_OBJ_2)
	$(COMMAND) $(COMMANDFLAGS) /c ..\..\config\remove $(CLU_OBJ_3)

# Makes clean as disributed
distclean:
	$(COMMAND) $(COMMANDFLAGS) /c ..\..\config\remove Makefile Makefile.top
	$(COMMAND) $(COMMANDFLAGS) /c ..\..\config\remove archive
	$(COMMAND) $(COMMANDFLAGS) /c ..\..\config\remove SPC.lib clu2c.time $(POUT).c
	$(COMMAND) $(COMMANDFLAGS) /c ..\..\config\remove $(C_OBJ_1)
	$(COMMAND) $(COMMANDFLAGS) /c ..\..\config\remove $(CLU_INT_1)
	$(COMMAND) $(COMMANDFLAGS) /c ..\..\config\remove $(CLU_INT_2)
	$(COMMAND) $(COMMANDFLAGS) /c ..\..\config\remove $(CLU_INT_3)
	$(COMMAND) $(COMMANDFLAGS) /c ..\..\config\remove $(CLU_OBJ_1)
	$(COMMAND) $(COMMANDFLAGS) /c ..\..\config\remove $(CLU_OBJ_2)
	$(COMMAND) $(COMMANDFLAGS) /c ..\..\config\remove $(CLU_OBJ_3)

# Makes really clean
realclean:
	$(COMMAND) $(COMMANDFLAGS) /c ..\..\config\remove Makefile Makefile.top
	$(COMMAND) $(COMMANDFLAGS) /c ..\..\config\remove archive
	$(COMMAND) $(COMMANDFLAGS) /c ..\..\config\remove SPC.lib clu2c.time $(POUT).c
	$(COMMAND) $(COMMANDFLAGS) /c ..\..\config\remove $(C_OBJ_1)
	$(COMMAND) $(COMMANDFLAGS) /c ..\..\config\remove $(CLU_INT_1)
	$(COMMAND) $(COMMANDFLAGS) /c ..\..\config\remove $(CLU_INT_2)
	$(COMMAND) $(COMMANDFLAGS) /c ..\..\config\remove $(CLU_INT_3)
	$(COMMAND) $(COMMANDFLAGS) /c ..\..\config\remove $(CLU_OBJ_1)
	$(COMMAND) $(COMMANDFLAGS) /c ..\..\config\remove $(CLU_OBJ_2)
	$(COMMAND) $(COMMANDFLAGS) /c ..\..\config\remove $(CLU_OBJ_3)

# Creates tag file
TAGS:

# Creates info file
info:

# Creates distribution
dist: $(DIST) $(PRE)
	@$(top_srcdir)/config/makedist $(distname) $(curdir) $(DIST)
	@$(top_srcdir)/config/makedist -p $(distname) $(curdir) $(PRE)

# Does some check
check:


#### Rules specific to this directory ####

# Creates stream.o
stream.o: $(srcdir)/stream.c
	$(CC) $(ALL_CFLAGS) -I$(top_srcdir)/lib/jaio -c $(srcdir)/stream.c

# Creates all the C files
cfiles: clu2c.time $(POUT).c

# Translates all the CLU source files to C files
clu2c.time: $(CLU_SRC)
	$(CLU2C) $(CLU2CFLAGS) --make
	echo clu2c.time > clu2c.time

# Pre-link
$(POUT).c: $(CLU_INT)
	$(PLINK_METHOD)

# Archives object files in this directory
archive: $(ALL_OBJ)
	$(AR) $(ARFLAGS) $(ARCHIVE) $(CLU_OBJ_1)
	$(AR) $(ARFLAGS) $(ARCHIVE) $(CLU_OBJ_2)
	$(AR) $(ARFLAGS) $(ARCHIVE) $(CLU_OBJ_3)
	$(AR) $(ARFLAGS) $(ARCHIVE) $(C_OBJ_1)
	$(RANLIB) $(ARCHIVE)
	echo archive > archive

# Creates makefiles for this directory and all the subdirectories
mkfiles:
	copy Makefile.top+$(config_mk)+$(srcdir)\Makefile.dos Makefile

# Forces a particular target to be made
always:


#### Suffix rules ####

.SUFFIXES:
.SUFFIXES: .o .c .clu

# Compiles CLU files
.clu.c:
	$(COMMAND) $(COMMANDFLAGS) /c ..\..\config\remove clu2c.time
	$(MAKE) clu2c.time

# Compiles C file to get object file
.c.o:
	$(CC) $(ALL_CFLAGS) -c $<
